### ISSUE TITLE
Structure of the Website

### ISSUE THREAD

**Issue by samu-wmde** [codingdavinci/relaunch2018#1]
Create basic website structure. 

Related Tasks: 

- [ ] #2 Event overview page
- [ ] #3 Single event page
- [ ] #4 News
- [ ] #5 FAQ
- [ ] #6 Static pages

**Comment by lohengruen** [comment]
Wireframe
https://www.figma.com/file/fMvBKPD5DZ2A99LgnR5RDoi7/LandingPage-Wireframe?node-id=1%3A2

**Comment by Snater** [comment]
Closing this ticket because it is not a task itself. Task aggregation is better managed by assigning labels.
