### ISSUE TITLE
Facts & Figures

### ISSUE THREAD

**Issue by samu-wmde** [codingdavinci/relaunch2018#10]
User Storie: As a founder I want to show show how many institutions have taken part in CdV etc on landing page so that to demonstrate to funders how wide the reach of CdV is and show where there is still work to be done.

Desgin Comment:
Section including numbers of datasets acquired, number of institutions participating, number of projects make. 

Dev Comment: 
BASIC: manually edited
NICE-TO-HAVE: generated numbers automatically updated when new content is added

**Comment by Snater** [comment]
The figures block reads all counts from the database: Number of users with role "institution", number of (published) Data Set content type instances, number of (published) Project content type instances.
