### ISSUE TITLE
Datasets: single dataset - include Gesamtgröße der Mediendateien in frontend

### ISSUE THREAD

**Issue by lucyWMDE** [codingdavinci/relaunch2018#100]
We'd like to show the "Gesamtgröße der Mediendateien" on the single dataset page. Can we add it to the generated statement about how many media files there are? Maybe as a second sentence "Gesamtgröße der Mediendateien: xxMB".

**Comment by Snater** [comment]
Added sentence. (Can be translated to German per admin interface.)
