### ISSUE TITLE
Projects / Verwendete Datensätze

### ISSUE THREAD

**Issue by lucyWMDE** [codingdavinci/relaunch2018#102]
Under "Andere Datensätze" can we also have the option to list information without any url behind it? Quite a few legacy projects have listed other components of their projects here (eg pre-trained neural nets, 3d models) without providing a url. Currently I'm not able to add this information to the listings as I get an error message when I try to save.

**Comment by Snater** [comment]
The field type of "Andere Datensätze" is Link, I would not recommend changing that. It would be possible to wrap that field with a field of type Short Text in a field group. So, you could independently have multiple data set links and multiple data set "offline" references. Bit of styling involved of course. The only thing that bites a bit is that it would only be meant for legacy projects—this field, I guess, should not be available to new project submissions.
A workaround could be to have a simple page on codingdavinci.de that you link to explaining the legacy nature of the link—just to put up some kind of alternative.

**Comment by lucyWMDE** [comment]
ok. Agreed. I'll try to figure out some kind of link I can use. Maybe it's not such a common problem afterall. I'll come back to you if it looks like it's going to be a bigger problem.
