### ISSUE TITLE
About page/Einzelne Seiten won't display

### ISSUE THREAD

**Issue by lucyWMDE** [codingdavinci/relaunch2018#103]
Both some old Einzelne Seiten (Über) and newly created ones (eg [About Coding da Vinci](http://codingdavinci.snater.com/de/about-coding-da-vinci)) cannot be viewed, either in preview whilst logged in, or logged out on the site. "The website encountered an unexpected error. Please try again later." is returned when you try to navigate to these pages. You had suggested it might have something to do with old paragraph references but it's a problem for brand new pages also... can you take a look? thx

**Comment by Snater** [comment]
I am unable to reproduce this on new pages. Is it a specific paragraph that needs to be added to the content body?

**Comment by lucyWMDE** [comment]
Ah - seems the problem is with the paragraph style I used to create the new page. If you start a page with "Textblock rechts", as soon as you try to add something in the left column it kills the page. "Textblock links" as the first paragraph doesn't create the same problem. Using "Textblock rechts" with no text/image/video in the left column is also fine as the first paragraph - it's only a problem when you try to add something in the left column.

**Comment by lucyWMDE** [comment]
I deleted the left column from the Textblockrechts paragraph at the top of the [Über](http://codingdavinci.snater.com/de/was-ist-coding-da-vinci) page and now it's working again. Would be great to put the video back though.

**Comment by Snater** [comment]
Nice debugging. :)
A silly coding typo was causing that error… :-/

**Comment by lucyWMDE** [comment]
great! it works :) I had to delete and redo the paragraph, but it seems fine. thx!
