### ISSUE TITLE
media upload - Urheber pflichtfeld

### ISSUE THREAD

**Issue by lucyWMDE** [codingdavinci/relaunch2018#104]
is there a way to disable the pflicht for the Urheber when uploading CC0 or PD images? Similar to our project or dataset upload forms...?

**Comment by Snater** [comment]
The easiest thing would be to just have "Urheber" not be a required field by unticking the checkbox on `[...]/admin/structure/media/manage/image/fields/media.image.field_creator`. As far as I remember, enforcing the Urheber on the project data set submission forms is just done in JavaScript. I guess I could add some JS to the image upload form as well, but not sure whether that is really necessary in that case.

**Comment by lucyWMDE** [comment]
agree. it's overkill. we can take care of it in the workflow - it's relevant for regional organisers and the Geschäftstelle. I'll un-check the box.
If it turns out to be a big problem in the future we can implement some javascript later.
