### ISSUE TITLE
Event Page: Textblock Rechts/Links, Linke/Rechte Spalte - can't add content

### ISSUE THREAD

**Issue by lucyWMDE** [codingdavinci/relaunch2018#108]
Seems to be a bug with paragraph style "Textblock Links" and "Textblock Rechts". Creating content in the primary Spalte works fine. Adding a title in the secondary Spalte works fine. But adding anything else (image, video, text) to the secondary Spalte doesn't work - the edits won't save. It returns the error message " Nicht zu übersetzende Felder können nur durch eine Aktualisierung der aktuellen Revision geändert werden."

**Comment by Snater** [comment]
This error may result from outdated paragraph references. Just tried on a new event node, added Textblock links, one with an image, another one with a video. Both worked fine.
Can you explain the exact steps to reproduce the error?

**Comment by lucyWMDE** [comment]
Just tested it with a new event - textblock links seems to work fine, but textblock rechts with anything in the left column kills the page. Also when further down the page. 

I've only been trying this on the pre-existing event pages. I'm worried that replacing them with new ones will break all the internal links (from datasets, from projects etc) causing a huge amount of content development work. Hopefully if the textblock rechts problem is solved we can rehabilitate those existing pages..

**Comment by Snater** [comment]
I am pretty sure that is just the same issue as #103, so I am closing this for the moment.
