### ISSUE TITLE
Event page: Box paragraph style seems buggy

### ISSUE THREAD

**Issue by lucyWMDE** [codingdavinci/relaunch2018#109]
I'm having trouble pinning down the problem with the Box paragraph style. Multiple bugs. 
e.g. I was able to successfully create a 50% yellow box with text-only content (Überschrift-2, body text, 2 buttons)... but
- attempting to change the colour,
- attempting to change the width, 
returned " Nicht zu übersetzende Felder können nur durch eine Aktualisierung der aktuellen Revision geändert werden." error. Is it possible that you can't change the colour or width of a box once you've initially created it? Is that a bug that can be fixed or is that a feature of some kind...?

**Comment by Snater** [comment]
I was able to reproduce that one. This appears to be a bug in Drupal, specifically https://www.drupal.org/project/drupal/issues/3025039
As a workaround, like suggested in the issue ticket, I have marked all fields not yet marked for translation translatable—which obviously does not make proper sense for static values like width and colour, but that seems to be the workaround for now.
