### ISSUE TITLE
Event page: logos paragraph image upload/selection

### ISSUE THREAD

**Issue by lucyWMDE** [codingdavinci/relaunch2018#111]
To add logo image files in this paragraph it would be useful to select from the site media archive - about half the logos are used for more than one event page. Either we have both the select-from-media-archive field AND the upload new media field or... if we have to choose one... I'd opt for the select-from-media-archive option. This is what we have for image selection for other paragraph styles - eg jury, box kopfbild - it's a bit annoying to have to leave the event page and upload directly to the media archive to upload a new image, but it's fine.

**Comment by Snater** [comment]
OK, changed to using files from the media repository. There is a rather new Drupal feature called Media Library which would considerably ease adding/managing the media files directly on the node edit form. But I would not enable that right now—let's just get things set up somewhat properly first. :)

**Comment by lucyWMDE** [comment]
agree. thx :)
