### ISSUE TITLE
(temporarily) unpublish content

### ISSUE THREAD

**Issue by lucyWMDE** [codingdavinci/relaunch2018#115]
For Einfache Seiten we have the option to unpublish a page should we need to take it down temporarily. 

We also had this function as a user story for datasets and projects in the brief. 
e.g. An institution realises then have copyright clearance issues with a dataset and asks for it to be taken down from the site whilst they resolve the problems. The draft and freigegeben versioning system doesn't do this - I think the only option we would have currently would be to delete the submission... or am I missing something?

And tbh I think we would also need it for news articles and events since these content types take quite a bit of work to create and I could imagine scenarios where there's some legal issue or similar and we need to temporarily take them down. It would be nice-to-have for other content types but not essential since they don't take so much work to produce.

Is it doable?

**Comment by Snater** [comment]
I just hope I did not create a permission mess here as the permissions / content moderation configuration have become a bit complex. The functionality to actually unpublish data sets / projects might have just gotten lost with introducing content moderation as that was configured to always create a new revision.
I have added an additional state "Unveröffentlicht" to these content types as well as page, article and event that may be applied to unpublish / hide the node now. Only Geschäftsstelle users should currently be configured to apply that specific content moderation state. So, if, for example, institutions should be allowed to unpublish their data set by themselves, the respective permission would need to be granted to the institution role as well.
