### ISSUE TITLE
Event page: Ansicht controls

### ISSUE THREAD

**Issue by lucyWMDE** [codingdavinci/relaunch2018#116]
When logged in as admin, the controls that you usually get at the top of the "Ansicht" view (Ansicht, Bearbeiten, Löschen, Neuste Version, Revisionen, Übersetzen) are not visible for Event pages. They can still be accessed from Bearbeiten modus... but it would be great to also get to them from Ansicht - main user story is to be able to switch between current published and Neuste Version in order to approve. I assume it has something to do with the fancy header. If this is simple, please implement. If not, we can live without.

**Comment by Snater** [comment]
Yes, it was generally not included in the rendered page output on pages with tiled headers (event pages, front page)—changed that.
