### ISSUE TITLE
Link "Presse" page

### ISSUE THREAD

**Issue by samu-wmde** [codingdavinci/relaunch2018#12]
User Storie: 
As a member of the press I want to easily find press information from the landing page so that I can write about CdV.

**Comment by Snater** [comment]
This ticket is rather fine grain, as general menu implementation is at #18, implementing the "Presse" page itself is at #33. Putting the link into the menu is ticking a checkbox in the Drupal backend.

**Comment by Snater** [comment]
I have added the "Presse" page to the menu, which will be reflected in the updated stating environment. (That last commit on this issue actually belongs to #13.) There is nothing to commit to the repository here, as that is specific content configuration, in contrast to technical configuration.

**Comment by lucyWMDE** [comment]
Reopening. @lohengruen do we need a link to Presse content from the landing page. Perhaps in the footer together with "contact". Or do you think the menu is enough?

**Comment by Snater** [comment]
I don't think a link in the footer would be recognized. A link in the menu is absolutely good enough in my opinion. If we are going to revisit the menu structure, I'd even put this into a less prominent 2nd level, if there is one.

**Comment by lohengruen** [comment]
The presse link is also included in the latest version of the main menu, but feel free to leave it out if you think that's too much.

https://www.figma.com/file/92ojS2H8Zjh7zoNY6BeyO1/LandingPage-Final?node-id=0%3A1
