### ISSUE TITLE
datasets with multiple license categories

### ISSUE THREAD

**Issue by lucyWMDE** [codingdavinci/relaunch2018#123]
Whilst checking over and massaging all the dataset imports we realised we have a minor but significant new use-case... I'd like to pick your brains for a smart solution. Sometimes a dataset submission includes data with multiple licenses. 
- DDB has numerous licenses
- Wikimedia Sverige (Nord 2016) has not defined any license in the first place - it'll be a mix of various CC licenses.

I think we need another category, 'je nach Objekt' for the licenses. We can make this in the taxonomy... but if this is the solution, I think we would still want these datasets to come up when we filter for specific licenses. e.g. filter for CC-BY and the "je nach objekt" tagged DDB dataset would still come up in the results. OR would it be better to be able to add multiple license categories to a single dataset submission..?

**Comment by Snater** [comment]
Hm, changing that now might be somewhat complex. But it seems it would be possible to just set the number of licences that may be selected to unlimited and that might actually be the easiest solution (add a bit of styling on top), apart from being the most proper solution, because "je nach Objekt" would add some obscure abstraction to the filter logic. However, this would enforce the obligation to be specific on licenses—so something like "a mix of CC licences" would not be possible. But would you really want to have something like that bending the whole data model, the filter logic and the fundamental intention of specifying licenses in the first place?

**Comment by gitstief** [comment]
I am very much in favor of allowing multiple licenses per data set. 

A little background: The DDB is comprised of a collection of data sets. At the moment we can‘t identify them persistently and with the flexibility we want. Right now we could formulate search requests (API calls) that would retrieve the objects belonging to a dataset. But we cannot name this data set yet and would want to be able to define data sets by lists of DDB ids. 

DDB is a special case, so I wouldn‘t make too much fuzz about it. I don‘t see the benefit of a „je nach objekt“ category (Am also not sure that I understand, how it conveys more information than „there are objects with different licenses in this set“ ... but that would be obious just by there being more than one license displayed. It‘s the same logic as with media types ... you can have a data set comprising images, audio and video, couldn‘t you? Or do you, @lucyWMDE, think users would interpret it as „I can choose either this license or that license for the whole data set“?)

If it was very easy to restrict the option of choosing more than one license to the Geschäftsstelle only, we would be fine, too, wouldn‘t we?

**Comment by lucyWMDE** [comment]
Cool - then let's go for applying multiple licenses. The only datasets allowed in CdV are versions of public domain, CC0, CC-BY, and CC-BY-SA... so I'd argue that, even if the portal includes datasets with further licenses, these are the only ones we'd need to list on our site. 

Users: I don't see the harm in making this an option available to institution users also. Maybe they someone wants to submit a collection that has data with differently licensed mediafiles. If some institution tries to use it in a weird way the responsible regional team should pick it up during the freigabeprozess.

thanks

In the DDB case we will create the entry with the admin or Geschäftstelle user account so can use the 1st level hierarchy tags and won't need to have a massive list with all version subtypes.

**Comment by Snater** [comment]
OK, enabled multiple media licences on data sets. I agree that institution users should be able to get along with the option of being able to add multiple licences.
