### ISSUE TITLE
event page: problem saving / broken links in winners paragraph

### ISSUE THREAD

**Issue by lucyWMDE** [codingdavinci/relaunch2018#124]
The system won't let us do any work on past event pages and save it, citing the " Nicht zu übersetzende Felder können nur durch eine Aktualisierung der aktuellen Revision geändert werden." error. It looks to be linked to the winners paragraph - seems all the importing and reimporting of projects has broken the links to the winning projects if they had already been added. However, if I try to re-enter the winning projects it still won't save. Re-entering the prize categories also doesn't fix the problem... I can keep trying to see if I can find a way to trick the system... but if you have a fix, pls halp.

**Comment by Snater** [comment]
Hm, I just added and deleted again a winner on the Berlin 2014 event which worked without error. Could you describe a specific way to reproduce the error? It might indeed result from some outdated references that might be quite silly to resolve.

You are right that with re-importing the projects, those received of course new node ids and the references to the winners were pointing to nodes not existing anymore.

**Comment by lucyWMDE** [comment]
ok. If I delete all the categories and start again I can solve the problem. All good. thx
