### ISSUE TITLE
project licences

### ISSUE THREAD

**Issue by ikyriazi** [codingdavinci/relaunch2018#125]
What is meabt by "Lizenz der Mediendateien"? Are these licences for other datasets (than the ones of the participating institutions)? If these are the licences of the participating institutions, is there a way to automatically copy/map the licences from the dataset pages? Will the project teams be in charge of providing this licence information, when the new website will be online?

**Comment by lucyWMDE** [comment]
> What is meabt by "Lizenz der Mediendateien"? Are these licences for other datasets (than the ones of the participating institutions)? If these are the licences of the participating institutions, is there a way to automatically copy/map the licences from the dataset pages?

A coding da vinci project can include different elements that can be differently licensed:
- data (submitted by the Datengebern to CdV)
- other openly-licensed grundlagen materials
- code (written by the team - may be built on pre-existing open source code)
- media files (any imagery/sound/video created by the team for the project)

"Lizenz der Mediendateien"  means the media files. 

> Will the project teams be in charge of providing this licence information, when the new website will be online?

yes

**Comment by ikyriazi** [comment]
I see! Thanks for the clarification!
