### ISSUE TITLE
project media files licences

### ISSUE THREAD

**Issue by ikyriazi** [codingdavinci/relaunch2018#127]
PG and I are unsure, if this is information is necessary. However, if the information should be indeed provided, we suggest the use of an open field to be completed by the project team, since the existing taxonomy doesn't provide all licences (e.g. audio file from Cyberbeetle, CC BY-NC-SA 3.0). If we added more options to the taxonomy, then this would complicate things for the data providers (who will be using the same taxonomy). In general, we are more in favor of an open field for the project team and a taxonomy for the data providers than having two different taxonomies (one for each target group).

**Comment by gitstief** [comment]
Free text fields are a very bad idea for this. We should use the controlled vocabulary/taxonomy.

If there is a stand-alone, i.e. not integrated in an application, media asset that is the outcome of a project, I don't see any reason why it should licensed more restrictively than the data of the data providers. 

Of course, this brings us back to the questions of the licensing of the applications itself. We had a similar issue in the context of the Inkubationsförderung questionnaire, where some developers – at least according to Lucy – were not willing to publish their projects under an open source licensing. In this area, I see a way to use certain variants of the GPL that allow precompiled components.

**Comment by lucyWMDE** [comment]
One of the rules of CdV is that projects entering the competition **have** to be published under an open license. The taxonomy currently contains all the permissible licenses - we won't add any more.  
However, it's very possible that we didn't control this so well in the past or that old projects are not clearly licensed. In those cases, just skip over the licensing fields. I don't think it's a big problem. But it is something the regional teams should control better going forward.

To SB's point about licenses for the Inkubationsförderung for further development of cdv projects (which really are only prototypes)... I see that as a separate issue - not something we need to discuss here.
