### ISSUE TITLE
project media files licences #2

### ISSUE THREAD

**Issue by ikyriazi** [codingdavinci/relaunch2018#128]
Continuing on the project media files licences issue:

1. For cases where "it's very possible that we didn't control this so well in the past" and no listed license applies, I agree with the possibility of skipping over this field (in other words, keeping it "optional"). However, I noticed that when clicking on "Lizenz der Mediendateien" (in the CMS, just to check what options exist) you get on the front end the heading "Lizenz der Mediendateien" automatically, even if you haven't selected an option. Is there a possibility to get this heading and the respective license, only when an option is actually selected? (e.g. see http://codingdavinci.snater.com/de/projekte/cyberbeetle)

2. The heading "Lizenz der Mediendateien" is here misleading. The way the project page is designed can lead the user to think that here we are referring to the Mediendateien of the contributing data providers (which follow on the screen). We suggest changing the heading to "Lizenz der eigens erstellten Mediendateien".

**Comment by lucyWMDE** [comment]
1 - created issue #130 
2 - edited heading text
