### ISSUE TITLE
"gemeinfrei" in license taxonomy

### ISSUE THREAD

**Issue by ikyriazi** [codingdavinci/relaunch2018#129]
I think "gemeinfrei" is not a specific license. It is an umbrella term for public domain and CC0, correct? Why is it listed here?

**Comment by gitstief** [comment]
I agree with @ikyriazi. In the strict sense of the word "gemeinfrei" means the PD mark, but it's often used in the sense that there are no restrictions for re-use and this includes all the CC0 data that have been put in the public domain by the rights holder before the legal time limit has been reached.

**Comment by lucyWMDE** [comment]
Hi both,
Please check with Philippe. I also thought the same initially, but he convinced me that "gemeinfrei" can't work as a translation of PD. It was through his feedback that we came up with the construction that we currently have. Either way, this is a content issue and won't require technical intervention.
thx
