### ISSUE TITLE
"gemeinfrei" #2

### ISSUE THREAD

**Issue by ikyriazi** [codingdavinci/relaunch2018#131]
I talked with PG and we have the opinion that "gemeinfrei" shouldn't remain as an option for future data providers. However we need it as a filter for the data that was already used with this description so far. Technical question:

Can we move all projects that were assigned to "gemeinfrei" to the more general category of "public domain/gemeinfrei" (one level higher)? After this has been completed, then delete the low-level "gemeinfrei" option. As PG informed me, the taxonomy is so constructed that the future data providers will be getting only the low level options to choose from, not the high-level ones.

**Comment by lucyWMDE** [comment]
Hi @ikyriazi,
just checking - is this still the plan? It hasn't been implemented yet but it's easy to do. I made an export of the datasets (you can do this [here](http://codingdavinci.snater.com/de/daten/export) via the "csv" button) there are currently 38 datasets listed as public domain +/or gemeinfrei. We can just 
- retitle the most frequently used 2nd level tag ([here](http://codingdavinci.snater.com/de/admin/structure/taxonomy/manage/licenses/overview))
- re-tag any remaining datasets
- delete any remaining unwanted 2nd level tags.
Would you be able to do this?

**Comment by ikyriazi** [comment]
Hi, @lucyWMDE! 
I am wondering why we are using the generic licenses (CC0) instead of having only the more specific ones (e.g. CC0 1.0)..
When one submits a new dataset, he/she has the option of choosing either a 1st-level or 2nd-level license.. Was this the intention? (I thought, it should be only the 2nd-level one) 

The problem with "gemeinfrei" is that it refers to the "end availability" of a dataset, not making clear whether the dataset was "given free" because it was in public domain or because of a CC0 license.
In any case I could check individually each case (thanks for the hint!). The only problem is that if I cannot detect what is meant with "gemeinfrei" in some cases (that is, PD vs. CC0), we need a way to keep the term "gemeinfrei" in the taxonomy (for filtering the related datasets in our interface) but exclude it from future use (in the next hackathons).

**Comment by lucyWMDE** [comment]
> When one submits a new dataset, he/she has the option of choosing either a 1st-level or 2nd-level license.. Was this the intention? (I thought, it should be only the 2nd-level one)

Shouldn't be possible when logged in with an institution or project team account. These users should only see 2nd level. If that's not the case let me know.

> The problem with "gemeinfrei" is that it refers to the "end availability" of a dataset, not making clear whether the dataset was "given free" because it was in public domain or because of a CC0 license.
> In any case I could check individually each case (thanks for the hint!). The only problem is that if I cannot detect what is meant with "gemeinfrei" in some cases (that is, PD vs. CC0), we need a way to keep the term "gemeinfrei" in the taxonomy (for filtering the related datasets in our interface) but exclude it from future use (in the next hackathons).

If I understand you right, "gemeinfrei" = PD or CC0?
Yeah - that sounds a bit messy... BUT there's only one dataset listed on the old site that uses it - https://codingdavinci.de/daten/#hmt - so it should be easy to resolve. I hope that means we can remove the term "gemeinfrei" from the taxonomy completely. Better if we only use "public domain". Are you happy to take care of that?

**Comment by ikyriazi** [comment]
You are right! Institutions or project teams can see only 2nd level! (I had logged in as admin, this is why I was seeing also the 1st level)
Yes, this is the problem with the "gemeinfrei". We should remove it completely.. I will take care of the licenses. ;)

**Comment by lucyWMDE** [comment]
Hi Ilias,
Is this taken care of? Can I close the issue? :)
thanks
Lucy

**Comment by ikyriazi** [comment]
Hi, Lucy! I haven't worked on this, and it is not on the top of my list for the moment. I could work on it even after the launch.. Would that be ok?

**Comment by lucyWMDE** [comment]
I guess. I think the last deadline for this would be cdv Niedersachsen project submission. I'll leave it in your hands. Pls don't forget it.

**Comment by ikyriazi** [comment]
The issue has been resolved.
