### ISSUE TITLE
tracking/cookies pop-up

### ISSUE THREAD

**Issue by lucyWMDE** [codingdavinci/relaunch2018#132]
Important request brough up by Philippe from the CdV Geschäftstelle. 
"since we are closing in on a hosting solution (lo and behold!) we will need a pop up on the new website indicating our tracking mode and the cookies used. The tracking will (most probably) be taken care of by the DNB (they use Matomo), so the right information to be referred to by the pop up will be here (see IX. Webanalyse durch Matomo).
Can you ask Henning to see to that?"

I'd assume drupal has an option for this... if there are stylistic choices I'm happy to look at the options. Thanks!

**Comment by Snater** [comment]
Will implement that on the next iteration. For future reference:
* https://www.drupal.org/project/eu_cookie_compliance
* https://matomo.org/faq/general/faq_157/

**Comment by Snater** [comment]
I have implemented a banner. Cookie blocking should be tested as soon as Matomo is set up.
There is a link "Weitere Informationen" in the banner, that should of course not lead to the frontpage, but to a Privacy policy page. So, a page should be created and the link to it can be set up at Konfiguration > EU Cookie Compliance in the section "DATENSCHUTZRICHTLINIE".

**Comment by ikyriazi** [comment]
I am assigning this to myself, in order to update the "Weitere Informationen" link, when the privacy policy page will be ready.

**Comment by ikyriazi** [comment]
I added a "Weitere Informationen" text with a link to the Datenschutz and Cookie policy. It should be good now.
