### ISSUE TITLE
Building Composer project states a Deprecation warning

### ISSUE THREAD

**Issue by mbuechner** [codingdavinci/relaunch2018#133]
> Deprecation warning: require.npm-asset/fortawesome--fontawesome-free is invalid, it should have a vendor name, a forward slash, and a package name. The vendor and package name can be words separated by -, . or _. The complete name should match "[a-z0-9]([_.-]?[a-z0-9]+)*/[a-z0-9]([_.-]?[a-z0-9]+)*". Make sure you fix this as Composer 2.0 will error.
> DrupalProject\composer\ScriptHandler::checkComposerVersion

**Comment by Snater** [comment]
Composer does not like that double dash anymore—replaced with an alternative endpoint.
