### ISSUE TITLE
audio/video for datasets

### ISSUE THREAD

**Issue by lucyWMDE** [codingdavinci/relaunch2018#136]
We implemented the option to include a video/audio file for single project pages. I should have asked for this for the datasets too - same functionalities. If it's simple to include this, please go ahead. thx

**Comment by Snater** [comment]
That should do it.

**Comment by lucyWMDE** [comment]
almost but not quite :/ May have the same problem for projects... here's an example...

video file: http://codingdavinci.snater.com/sites/default/files/2019-11/Telefon_0.mp4
for use with this dataset: http://codingdavinci.snater.com/de/daten/telefone-ruftoene-und-geraeusche

I can upload the file, I can see it here http://codingdavinci.snater.com/de/admin/content/files, the video will play in as a stand-alone file in the browser, but it's not rendered correctly and won't play in the dataset page http://codingdavinci.snater.com/de/daten/telefone-ruftoene-und-geraeusche.

I also don't see the image I've uploaded as a cover image for the video.

I've tested for projects and everything seems to work fine, eg http://codingdavinci.snater.com/de/projekte/projekt-name-des-projekts

**Comment by Snater** [comment]
My bad, missed something when duplicating the functionality. Works now.

**Comment by lucyWMDE** [comment]
mmuuh... :/ almost. this is the ticket that will never die! We can play it now, but there's something weird that's causing the image to render huge on the dataset page when a film or audio file is added. See http://codingdavinci.snater.com/de/projekte/projekt-name-des-projekts - I've tested with both audio and film - same problem.

**Comment by Snater** [comment]
Do you mean the greenish image in the background? That has always been there. I can remove it.

**Comment by lucyWMDE** [comment]
weird. It looks fine now. It wasn't the background.. the videos themselves were rendering as super huge. But it looks fine now. No idea what was going on. Thanks anyway!
