### ISSUE TITLE
dataset institution search seems to be broken

### ISSUE THREAD

**Issue by lucyWMDE** [codingdavinci/relaunch2018#137]
When I type in the name of an institution into the search field it offerns a nice dropdown autocomplete option, but when I select it it converts to a number. If I then press return to start the search, or click "filter anwenden" I get no results.
Similarly, if I just type in a query without using the autocomplete, then press return, I don't get any hits.

I can use the Volltextsuche instead, but this is not a solution.

**Comment by Snater** [comment]
Strange. This worked before, but I think the method was different. Like mentioned that filtering logic is kind of fragile. The behaviour of the institution filter is actually a text search limited to the institution name (the name of the user being the author of the node). I hope this works kind of as expected now :-/
