### ISSUE TITLE
Dataset overview page word-wrap

### ISSUE THREAD

**Issue by lucyWMDE** [codingdavinci/relaunch2018#139]
Check out "Verwaltungsinformationszentrum des Bezirksamtes Charlottenburg­ - Wilmersdorf von Berlin" as an institution username for this dataset http://codingdavinci.snater.com/de/daten/handschriften-aus-charlottenburg

On the overview page the name really overshoots the box its supposed to fit in.

It's not a very common problem, but I think it might be sensible to anyway apply "word-wrap:word-break" to the header style for this view. If it's straightforward could you do it pls. thanks!

I don't think it's a problem for the Project archive since we use a smaller font in that area there.

**Comment by Snater** [comment]
Don't forget about `&shy` allowing to manually define word breaks.

**Comment by lucyWMDE** [comment]
Doesn't seem to be enabled...  eg http://codingdavinci.snater.com/de/daten/handschriften-aus-charlottenburg
see name of institution, "Verwaltungs&shy;informations&shy;zentrum des Bezirksamtes Charlottenburg­ - Wilmersdorf von Berlin" - also in dataset card version on the dataset overview page.  
... or am I doing it wrong?

**Comment by Snater** [comment]
OK, I was a bit wrong on suggesting to use the entity. I did not have in mind that the value is the actual username. Filling a username with HTML entities is a thing that should rather be avoided as it might have undesired implications. Also, users assign their username by themselves when creating an account, so we could not just skip escaping the username when displaying it. The `&shy;` entity itself should not do any wrong and I could add a hack to just allow that tag in the username: That is replace `&shy;` with a placeholder, escape the username and replace the placeholders with `&shy;` again—in the template language this looks like `institution_name|raw|replace({'&shy;': '%shy%'})|escape|replace({'%shy%': '&shy;'})|raw`. That seems to work an still replace things like HTML tags. But just as it looks, it does not feel correct.

**Comment by lucyWMDE** [comment]
This is still an issue... albeit a small one. `&shy` tags are used. They function well in the [dataset card on the overview page](http://codingdavinci.snater.com/de/daten?event%5B328%5D=328&search=&institution=&page=1) making nice hyphenated linebreaks, but on the dataset itself where the institution name is listed in the header you can see the tags. Can we fix this? It likely doesn't apply to many datasets so we could live with the bug if we have to.

**Comment by Snater** [comment]
There was just something missing causing the &shy entities not replaced on the data set page.
