### ISSUE TITLE
Potential participant call to action

### ISSUE THREAD

**Issue by samu-wmde** [codingdavinci/relaunch2018#14]
User Storie: As a potential hackathon participant or GLAM institution I want to find out how to sign up/register my interest so that I can get involved

@lucyWMDE: We don't have a communication strategy at the moment, there might be a newsletter at some point in the future... but for now we just need a button/call-to-action that sends users to a page where we describe how they can get involved/sign-up etc

**Comment by Snater** [comment]
Block is in place.
