### ISSUE TITLE
Test scenario: ONBOARDING NEW REGIONAL TEAM 

### ISSUE THREAD

**Issue by lucyWMDE** [codingdavinci/relaunch2018#141]
- Geschäftstelle creates a draft version Muster event page to hand over to a new hypothetical regional team. 
[please build a basic event page for a hypothetical future event. Don't worry about the content too much - final content and design is still under development together with the designer. This is just a technical test for generic editing rights]
- Geschäftstelle sets up accounts for a new hypothetical regional team in drupal and gives them access to those accounts and to edit the page for their event. 
(navigate to Benutzer area in drupal, create account(s) with "event team" roll. On the Muster event page add these users to the field "team" from the dropdown)  
- hypothetical Regional team makes edits to the event page, then requests freigabe from the Geschäftstelle (I think that's how we set it up). 
- Geschäftstelle approves/disapproves/publishes the content. 
[test editorial process]
- Regional team makes additional edits, publishes again... etc 
[every action you can think of that a regional team would perform under supervision of the Geschäftstelle]

**Comment by ikyriazi** [comment]
I am starting with the most significant issues/questions here:
> What is the difference in the user rights between admin and Geschäftsstelle??
> Creating/deleting an event is made only by an admin. The "event team" user can only edit. Is it supposed to be like this? Just checking.
> Created user (e.g. ilias2_event) can edit another user (e.g. ilias_event_changed)!! (Bug) 
> As event team I didn't have to ask for "freigabe" from the GS after saving any changes! The changes were implemented anyway.
> The CMS in general gives the possibility to users to play with the structure of the events page (section "Abschnitte"). This is a principle that I actually find very problematic. Users should be given the possibility to add *content* instead of *blocks/visual elements* (this is how it is usually done, as far as I know). It should be only in the position of an admin to change appearances. Giving this kind of freedom would disturb the consistency of the website, imho.

(following comments deal with more detailed aspects)

**Comment by ikyriazi** [comment]
1. *Geschäftstelle* creates a draft version Muster event page to hand over to a new hypothetical regional team.
// Page: http://codingdavinci.snater.com/de/node/add/event //

Anzeigedatum:
> I would suggest, there should be an indication about what this/these date(s) is/are to be used for (contentwise).

Selecting Farbschema: 
> Is there an option to see the colors when making a selection? Alternatively, could there be a link to a page to see the possible color schemas? Could it be so configured that by selecting a schema for an event, it is excluded from reuse in any future selections/events?
> Why are there so many options?

Kacheln:
> Will this image be there for every event? Why is it there by default? An explanation is needed here.

Text-intro:
> An explanation of what this text will be used for would really help. Otherwise, I feel "out of context". Maybe have a sample text as an example?
> Ausrichtung: is there actually room for "playing" here?

Speichern unter:
> Please explain the differences between the three options (Entwurf vs. unveröffentlicht??). I selected "Entwurf"..

// Event page is created: e.g. http://codingdavinci.snater.com/de/events/test-event-19112019-ilias //

Other notes:
> When you have a translation and you want go back to editing the event, you get the option "Speichern (alle Übersetzungen)" at the bottom. However, this is misleading. I clicked on it and although at the overview page I had both pages (original and translated) under the same status (e.g. veröffentlicht), only one of the two was really public..

**Comment by ikyriazi** [comment]
2. Geschäftstelle sets up accounts for a new hypothetical regional team in drupal and gives them access to those accounts and to edit the page for their event.
// Page: http://codingdavinci.snater.com/de/admin/people/create //

General notes:
> Although the admin has given only an "event team" permission to the user, the user is assigned by default also a "project team" (bug!) and an "angemeldeter benutzer" role . The admin has to revisit the user profile to deselect the "project team" role. When the admin re-saves the user's profile, his/her "angemeldeter benutzer" status disappears from his/her roles in the list of users. What is "angemeldeter benutzer" used for, anyway?

> When the user receives access to his/her account, he is seemingly "offered" the chance to choose between three roles (Project team, institution, event team). However, this is misleading. Whatever role the user selects, it is always overwritten by the decision of the admin. It would be better, if these options weren't there.

**Comment by ikyriazi** [comment]
3. (Next steps depend on getting permission from the GS, which doesn't seem to operate yet)
