### ISSUE TITLE
Test scenario: CULTURAL INSTITUTION SUBMITS DATASET TO REGIONAL EVENT

### ISSUE THREAD

**Issue by lucyWMDE** [codingdavinci/relaunch2018#142]
- Hypothetical regional organisers email invitation to hypothetical cultural institution to create an account in the system (this link: http://codingdavinci.snater.com/de/user/register).
- Hypothetical cultural institution creates new account, edits profile information, submits hypothetical dataset for review
[please try to imagine everything that could go wrong - institution exits process in the middle, looses password, wants to save midway through dataset submission and return to it later - see if it's self-explanatory or where they will need more support]
- Regional team +/or Geschäftstelle (I forget how we defined it - either way, it's now up to you at the Geschäftstelle to define the best workflow based on your experience - make sure to test that regional team has appropriate access) reviews the submission, maybe makes some edits in the description, maybe requests more information from the cultural institution... eventually publishes the dataset.
[please check how the system can support you to do the work you need to do here]
- Geschäftstelle/regional team/cultural institution realises at a later data that there is a problem with the dataset and edits it... Geschäftstelle/regional team/cultural institution realises at a later data that there is a problem with the dataset and unpublishes it.
[please be critical here about who has/should have the rights to do what]

**Comment by ikyriazi** [comment]
General issues:
> There is a bug when creating as [admin] a new user profile: Although I am checking the box "Benutzer über neues Konto benachrichtigen" the user doesn't always get an email to configure his/her profile. This needs further testing. I didn't have an issue with this the other day. (bug)

> The CMS is currently so configured that a collection/dataset/sammlung can be authored only by a single user profile (named "institution"). Shouldn't it be not so that multiple users (multiple e-mail addresses) could have access to the same collection and edit it?? (I mean multiple members of the institution, not users with other roles, like admin, GS, events team, etc.)

> In terms of information architecture, I consider more appropriate to have a connection with the institution also at the collection/Sammlung/dataset level (intellectual level), rather than the user profile level (authorship level). In other words, I miss the institution as parent of the collection. At the moment it serves only as "author" of a dataset.

> Current dataset statuses do not function properly across users. Also, duplicate terms are in use for the same status. Also, the status at the overview page does not always correspond with the status within the collection page. A new taxonomy of statuses across multiple users has to be defined:

(Words in bold indicate the action that triggers the status appearance for the other users)
| Institution speichert als | Übericht für Institution | Event Team speichert als | Übersicht für Event Team | Admin speichert als | Übersicht für Admin |
| -- | -- | -- | -- | -- | -- |
| **Entwurf** | Entwurf | - | - | - | Entwurf |
| **Bitte prüfen** | In Prüfung durch ET | - | Bitte prüfen | - | In Prüfung durch ET |
| - | In Prüfung durch ET | **Zwischenstand** | Bitte prüfen | - | In Prüfung durch ET |
| - | In Prüfung durch GS | **Freigegeben** | In Prüfung durch GS | - | Bitte prüfen |
| - | In Prüfung durch GS | - | In Prüfung durch GS | **Zwischenstand** | Bitte prüfen |
| - | Veröffentlicht | - | Veröffentlicht | **Veröffentlicht** | Veröffentlicht |

Comments:
- The website shows only content that was **last published (veröffentlicht)** from the GS (Admin)
- The institution should always have the option to make changes and save the dataset with the status "bitte prüfen" (even after it has been published).
- The GS (Admin) should always have access to the content and be able to publish it even with no Institution- or ET-interference (in urgent cases).
- After the hackathon (we need a date value here), changes in the dataset should trigger an email to the GS/Admin directly for reviewing and publishing (no ET-review is needed).
- "Save as" options for Institutions: Entwurf, Bitte prüfen (even if the content has been already published; changes can come at a later point, or even a later hackathon)
- "Save as" options for ET: Zwischenstand, Freigegeben
- "Save as" options for GS (Admin): Zwischenstand, Veröffentlicht

**Comment by ikyriazi** [comment]
1. Hypothetical regional organizers email invitation to hypothetical cultural institution to create an account in the system (this link: http://codingdavinci.snater.com/de/user/register).

Page "Neues Benutzerkonto erstellen":
> Both the submit button and the link at the bottom left have the same name, which makes it misleading. I am guessing the link at the bottom left is supposed to bring to a new registration page. I would use "Absenden" or "Registrieren" for the button.

> Clicking the button doesn't send an email to the user, to configure hir/her password etc.!! (Bug)

**Comment by ikyriazi** [comment]
2. Hypothetical cultural institution creates new account, edits profile information, submits hypothetical dataset for review
[please try to imagine everything that could go wrong - institution exits process in the middle, looses password, wants to save midway through dataset submission and return to it later - see if it's self-explanatory or where they will need more support]

-- 2a. Creating / filling out the user's profile (z.B. http://codingdavinci.snater.com/de/user/893/edit) --

> If a new author (e-mail address) from an already existing institution wants to create a new collection, he/she will have to retype the institution's title in the institution field of the user-profile-page ("Name Ihrer Kulturinstitution"). However, this field does not automatically retrieve an index of the already submitted institutions. As a result, an alternative naming or typo can result in the creation of a new institution, although we are talking about the same one. (This is not an issue, when having a single user for an institution)

> The institution field has to become compulsory when completing the user profile. If not completed, this information will be absent in the website (and the list/index of institutions).

**Comment by ikyriazi** [comment]
-- 2b. Creating / filling out the collection/dataset --

General note:
> Every new entry should be named "Datenset/Sammlung". In this case, under the institution's (or user's) profile we would have:

| Was | Should be |
| -- | -- |
| Bereitgestellte Datensätze | Bereitgestellte Datensets/Sammlungen |
| Neue Datensatz-Beschreibung anlegen | Neue(s) Datenset/Sammlung anlegen |

Name/Titel der Sammlung:
> There are cases where the same collection may be used in a new hackathon, however with a different dataset or a different version of the original dataset. What should we do in this case? One option would be to have an indication stating that a new page should be created for the new dataset. If on the other hand we want to have both datasets under the same "Sammlung"-page, then we should ask for appropriate differentiation in dataset naming at the links area.

Datensatztyp:
> A new list of Datensatz-types is needed (discussed also with Philippe). Please, change the two following options accordingly:

| Was | Should be |
| -- | -- |
| Datenportal (mehrere Datensätze aus verschiedenen Quellen) | Datenset (mehrere Datensätze aus verschiedenen Quellen) |
| Datenportal (mehrere Datensätze von einer Institution) | Datenset (mehrere Datensätze von einer Institution) |
The option "Einzelner Datensatz" remains as it is.
(The above changes should be also applied to the already existing datasets from previous hackathons.)

> Important is also to change the sequence of available options, based on the value most frequenctly in use, that is:
1. Datenset (mehrere Datensätze von einer Institution)
2. Datenset (mehrere Datensätze aus verschiedenen Quellen)
3. Einzelner Datensatz

> By the option "Datenportal (mehrere Datensätze aus verschiedenen Quellen)" there should be also an additional text like "please indicate additional data sources in the Beschreibung-Block"

Schlüsselwörter:
> My questions: 1. Could the website visitor have access to a cloud of all keywords and be able to choose among them? 2. Can an admin find somewhere all keywords used and eventually delete some of them, or replace them? The problem is that the same concept may be repesented by different keywords; as a result, grouping under the same concept is not always possible.

**Comment by ikyriazi** [comment]
-- 2c. Submitting hypothetical dataset for review --

Important note:
> Currently, when submitting the dataset description, the status of the dataset gets the value "freigegeben", although it still waits for review by the event team. The right terminology here would be: "In Prüfung durch ET" (see also general note above about statuses)

**Comment by ikyriazi** [comment]
3. Regional team +/or Geschäftstelle (I forget how we defined it - either way, it's now up to you at the Geschäftstelle to define the best workflow based on your experience - make sure to test that regional team has appropriate access) reviews the submission, maybe makes some edits in the description, maybe requests more information from the cultural institution... eventually publishes the dataset.
[please check how the system can support you to do the work you need to do here]

General note:
> Dataset submission needs some further testing: there was a case where the event team/GS was not informed about the event submission, or the e-mail was sent (half) an hour later

Legacy:
> What is this text field for??

Beschreibung:
> The event team doesn't have permission to make changes in the text, after submitted by the institution for review. 
Message: "Dieses Feld wurde deaktiviert weil Sie nicht die erforderlichen Berechtigungen haben, um es zu bearbeiten."
This shouldn't be the case! Both event team and GS/Admin should have the right to change the content of institutions or project teams.

**Comment by ikyriazi** [comment]
4. Geschäftstelle/regional team/cultural institution realises at a later data that there is a problem with the dataset and edits it... Geschäftstelle/regional team/cultural institution realises at a later data that there is a problem with the dataset and unpublishes it.
[please be critical here about who has/should have the rights to do what]

> Please see above comment for statuses regarding re-editing content after having been published. (No "unpublish" status is needed; the latest version is always the version published from the GS/Admin. If an urgent change is needed, it can be directly applied by the GS/Admin)

**Comment by ikyriazi** [comment]
One more thing: there should be a field that would enable institutions to upload the pdf /video file used in their kick-off presentation.
