### ISSUE TITLE
Test scenario: PROJECT TEAM SUBMITS PROJECT

### ISSUE THREAD

**Issue by lucyWMDE** [codingdavinci/relaunch2018#143]
- Hypothetical regional organisers email invitation to project team representative to create an account in the system (this link: http://codingdavinci.snater.com/de/user/register).
- Hypothetical project team representative creates account, submits project for review
[please try to imagine everything that could go wrong - team representative exits process in the middle, looses password, wants to save midway through project submission and return to it later - see if it's self-explanatory or where they will need more support]
- Regional team +/or Geschäftstelle (I forget how we defined it - either way, it's now up to you at the Geschäftstelle to define the best workflow based on your experience - make sure to test that regional team has appropriate access) reviews the submission, maybe makes some edits in the description, maybe requests more information from the team representative... eventually publishes the dataset.
[please check how the system can support you to do the work you need to do here]
- Geschäftstelle/regional team/team representative realises at a later data that there is a problem with the project and edits it... Geschäftstelle/regional team/team representative realises at a later data that there is a problem with the project and unpublishes it.
[please be critical here about who has/should have the rights to do what]

**Comment by ikyriazi** [comment]
General issues:

> Some of the issues discussed in the dataset submission apply also here; especially with regard to the project statuses, depending on where we are situated in the editing/review process.
(Words in bold indicate the action that triggers the status appearance for the other users)

| Projektteam speichert als | Übericht für Projektteam| Event-Team speichert als | Übersicht für Event-Team | Admin/GS speichert als | Übersicht für Admin/GS |
| -- | -- | -- | -- | -- | -- |
| **Entwurf** | Entwurf | - | - | - | Entwurf |
| **Bitte prüfen** | In Prüfung durch ET | - | Bitte prüfen | - | In Prüfung durch ET |
| - | In Prüfung durch ET | **Zwischenstand** | Bitte prüfen | - | In Prüfung durch ET |
| - | In Prüfung durch GS | **Freigegeben** | In Prüfung durch GS | - | Bitte prüfen |
| - | In Prüfung durch GS | - | In Prüfung durch GS | **Zwischenstand** | Bitte prüfen |
| - | Veröffentlicht | - | Veröffentlicht | **Veröffentlicht** | Veröffentlicht |

Comments:
- The institution should always have the option to make changes and save the dataset with the status "bitte prüfen" (even after it has been published).
- The GS (Admin) should always have access to the content and be able to publish it even with no Institution- or ET-interference (in urgent cases).
- After the hackathon (we need a date value here), changes in the dataset should trigger an email to the GS/Admin directly for reviewing and publishing (no ET-review is needed).
- "Save as" options for Institutions: Entwurf, Bitte prüfen (even if the content has been already published; changes can come at a later point, or even a later hackathon)
- "Save as" options for ET: Zwischenstand, Freigegeben
- "Save as" options for GS (Admin): Zwischenstand, Veröffentlicht

**Comment by ikyriazi** [comment]
1. Hypothetical regional organisers email invitation to project team representative to create an account in the system (this link: http://codingdavinci.snater.com/de/user/register).

> Why is the indication "Daten Ihrer Kulturinstitution" on this page?

Passwort-Vorschläge:
> There is the hint: "Es müssen mindestens 12 Zeichen sein". However it still works with fewer symbols. Shouldn't it be "sollen" instead of "müssen"?

**Comment by ikyriazi** [comment]
2. Hypothetical project team representative creates account, submits project for review
[please try to imagine everything that could go wrong - team representative exits process in the middle, looses password, wants to save midway through project submission and return to it later - see if it's self-explanatory or where they will need more support]

Page "Projekt erstellen":
> Shouldn't the project's "Bild" (and license) be compulsory elements?

> Under links it would be easier for the users to have a drop-down menu with the options "Projekt-Website, Projekt-Demo, Dokumentation, Quelltext" as well as "Other" with the automatic option to suggest a new category. The way it is now, it is not made clear what exactly is expected in the "Link-Text" field and how it is expected to look like in the website (end-result).

> An additional field for adding the project presentation (pdf/video to be presented in the Preisverleihung) is also necessary.

> Similarly as above, it would be much clearer by "Team-Mitglieder" to have a drop-down menu for the Links section (e.g. Twitter, Github, other/filling out, etc.) 

(When saving as Entwurf, the events-team (e.g. ilias_event_changed) doesn't receive a notification --> this is correct.)

Saving the project as "freigegeben":
> "freigegeben" should change to "bitte prüfen"

> The Following notification appears: "Danke schön! Das verantwortliche Projekt-Team wurden benachrichtigt und werden Deine Projektbeschreibung in Kürze freischalten." 
This has to change to:
"Dankeschön! Das verantwortliche "Veranstalterteam wurde benachrichtigt und wird Deine Projektbeschreibung in Kürze freischalten."

> No email was received by the events-team (in my testing: ilias_event_changed)

**Comment by ikyriazi** [comment]
3. Regional team +/or Geschäftstelle (I forget how we defined it - either way, it's now up to you at the Geschäftstelle to define the best workflow based on your experience - make sure to test that regional team has appropriate access) reviews the submission, maybe makes some edits in the description, maybe requests more information from the team representative... eventually publishes the dataset.
[please check how the system can support you to do the work you need to do here]

> The events-team cannot change anything in the field "Beschreibung" --> this should change

> There is no status to indicate a "Zwischenstand" status. 

> The saving status "veröffentlicht" should change to "freigegeben". The "publication" should NOT take place on the events-team level but should be later taken over by the GS.

**Comment by ikyriazi** [comment]
4. Geschäftstelle/regional team/team representative realises at a later data that there is a problem with the project and edits it... Geschäftstelle/regional team/team representative realises at a later data that there is a problem with the project and unpublishes it.
[please be critical here about who has/should have the rights to do what]

> Everyone can already change the content directly, even when it has been already published ("unpublish" is unnecessary). This is good so, however the process should be like the following, **after publication of the content**:
- The project team makes changes --> Review and direct publication from the GS (no intermediate review by the events-team)
- The events team makes changes --> Review and publication from the GS
- The GS makes changes --> Publication

> According to my understanding, in case a whole project needs to be deleted, there is already a 'delete' possibility. If this is correct, then there is no need to "unpublish", right?
