### ISSUE TITLE
General (Backend Basic functions) 

### ISSUE THREAD

**Issue by samu-wmde** [codingdavinci/relaunch2018#15]
In general (backend, basic functions)
- Bug-free responsive design
- 1st & 2nd level navigation 
- Implement measures for Barrierefreiheit where relevant
- Images should render faster
- Include twitter cards and Facebook equivalent if possible <-- check GDPR compliance
- Redirect all old links

Related Tasks:

- [ ] Zweisprachigkeit #16 
- [ ] Navigation #18  
- [ ] Editing #19 
- [ ] PIWIK #30

**Comment by Snater** [comment]
I'd close the ticket because it is more or less just plain structural--which would be managed better by assigning labels. Do we really aim for link redirection? I am not sure we open that can of worms. For Daten and Projekte, somebody would need to *manually* map every single link…

**Comment by Snater** [comment]
Opened #68 on porting the archives. Closing this ticket as it is to general / plain structure.
