### ISSUE TITLE
two-line CdV Logo replacement

### ISSUE THREAD

**Issue by ikyriazi** [codingdavinci/relaunch2018#154]
According to our new styleguide, only the single-line CdV Logo will be used. Although it seems to have been implemented in most places, could you replace it also in the home page (http://codingdavinci.snater.com/) at the top?

**Comment by lucyWMDE** [comment]
Hi Ilias, Not sure what you mean - can you provide specific examples. thanks.

**Comment by ikyriazi** [comment]
Hi, Lucy! I am attaching a photo. Shouldn't the single-line logo be used here?
<img width="599" alt="Screen Shot 2020-01-23 at 2 08 59 PM" src="https://user-images.githubusercontent.com/2911489/72987205-3344a600-3dea-11ea-9f57-4b309909f158.png">

**Comment by lucyWMDE** [comment]
the website was not within the remit of the print redesign. In fact the website acts as inspiration for the print redesign. I looked through the new CI guidelines and found what you are referring to... I hadn't realised that had been the outcome. It's a little incongruous with the website, but I don't think it needs to be a problem. 
Personally I don't see that we have to change the website. If we did it would have to be an additional feature request beyond the scope of the current relaunch... Please consult with Philippe and determine whether you think this is really necessary.

**Comment by ikyriazi** [comment]
Hi, Lucy! Philippe and I don't think it is necessary for now. It can stay, as it is.
