### ISSUE TITLE
"Login" link at the bottom of each page

### ISSUE THREAD

**Issue by ikyriazi** [codingdavinci/relaunch2018#155]
There has been a small mistake at the "Login" link:
"L" links to: https://test.codingdavinci.de/impressum-datenschutz
"ogin" links to: https://test.codingdavinci.de/user

The whole word has to be linked to https://test.codingdavinci.de/user

**Comment by ikyriazi** [comment]
I just changed it myself, but I don't see the change yet in "view modus"

**Comment by lucyWMDE** [comment]
This will be updated when @Snater implements the slightly modified footer from the design overhaul

**Comment by Snater** [comment]
The HTML generated by the editor was a bit confused. In such cases, you might want to switch to "Quelltext" in the editor to untangle the tags manually. I fixed it, should be OK when I have re-uploaded the database.
