### ISSUE TITLE
Obfuscate email

### ISSUE THREAD

**Issue by ikyriazi** [codingdavinci/relaunch2018#156]
We would like to avoid the release of email adresses due to spam etc. Could you install a module like this one (https://www.drupal.org/project/obfuscate_email) to obfuscate/encrypt them?

**Comment by ikyriazi** [comment]
We would like to avoid the release of email adresses due to spam etc. Could you install a module like this one (https://www.drupal.org/project/obfuscate_email) to obfuscate/encrypt them?

**Comment by mbuechner** [comment]
I would rate that issue as very important.

**Comment by lucyWMDE** [comment]
Slight changes to the footer through the design overhaul are still to be implemented. Will be great to combine this issue with those updates.

**Comment by Snater** [comment]
Added https://www.drupal.org/project/spamspan

**Comment by mbuechner** [comment]
E-Mails are not all obfuscated. 😞 

See https://test.codingdavinci.de/de/projekte/interaktive-karte-fuer-euregio-historynet

**Comment by Snater** [comment]
Config was setup for text formats. Dedicated email fields have to specifically be configured to make use of the SpamSpan module. I changed the display format of that particular field to `E-Mail SpamSpan` and obfuscation is invoked there as well now—also for the email displayed on institution user pages. If there are email fields missing, just apply the `E-Mail SpamSpan` output format there as well.
