### ISSUE TITLE
Landing page: Bevorstehende Events - layout

### ISSUE THREAD

**Issue by lucyWMDE** [codingdavinci/relaunch2018#157]
Text styles and layout of event cards is different to figma (size of {COD1NG DA V1NC1} logo, placement of link etc) - do we want/need to change it?

**Comment by stffb** [comment]
Yes, I would suggest to stay with the figma design.
Especially the size of {COD1NG DA V1NC1} logo should be smaller so the city is more outstanding. As well as the spacing to the city shoul be smaller.
