### ISSUE TITLE
body text font size

### ISSUE THREAD

**Issue by lucyWMDE** [codingdavinci/relaunch2018#160]
body and H3 has been implemented as 22px which should be 20px according to figma… this is true for 
- Landing Page section “Was ist mit Kulturdaten möglich?” body text
- Landing Page section (Green & white) “Coding da Vinci für Kulturistitutionen” and “Coding da Vinci für technikaffine und kulturbegeisterte Communities” body text
- News teaser H3 headers
- Einfache Seite general body text and H3 headers
... likely other pages I haven't checked yet. 

I'd like to have an opinion from both of you about how to resolve this.

**Comment by stffb** [comment]
We should go for 20. 
22 is too big in my opinion.
