### ISSUE TITLE
Landing Page: (Green & white) “Coding da Vinci für Kulturistitutionen” and “Coding da Vinci für technikaffine und kulturbegeisterte Communities”

### ISSUE THREAD

**Issue by lucyWMDE** [codingdavinci/relaunch2018#161]
- headings should wrap into left column alongside body text in right column.
- “Coding da Vinci für technikaffine und kulturbegeisterte Communities” - “Details zur Teilnahme” link under the body text is missing.
- In figma, left margin of body text column is further right - please implement

**Comment by lucyWMDE** [comment]
last part still open: 
- “Coding da Vinci für technikaffine und kulturbegeisterte Communities” - “Details zur Teilnahme” link under the body text is missing.

**Comment by lucyWMDE** [comment]
update: I figured out how to edit the text, but somehow my additional <p> didn't inherit the styles it needs to - the link came out black when it should be white. Can you help?

**Comment by Snater** [comment]
That should do it.
