### ISSUE TITLE
Landing Page/Project overview page: Project cards/previews

### ISSUE THREAD

**Issue by lucyWMDE** [codingdavinci/relaunch2018#163]
- [ ] H3 looks different in figma - should be dark grey
- [ ] Space between H3 and body text larger than in figma.
- [ ] Space between body text and first row of tags slightly larger than in figma.
- [ ] Vertical spacing between tags looks too large - should be 8px? Even between different categories of tags. 
- [ ] tag height should always be 22px - event and project-type tags are both implemented as 24px - pls correct
- [ ] There shouldn’t be a left indent before project-type tags
- [ ] "place tags all next to each other as long as the space allows it. There is no need for separation between disabled and active tags" - no line breaks between tag categories.
- [ ] in project overview page we should have 3 columns of projects rather than 2.
- [ ] Prize categories are no longer displayed as tags - please remove. 
- [ ] Instead we display prizes as small blue labels over the top right corner of the thumbnail - see figma/subpages/buttons & links

**Comment by stffb** [comment]
»Vertical spacing between tags looks too large - should be 8px? Even between different categories of tags.« —— I suggest to also place them all next to each other as long as the space allows it. There is no need for separation between disabled and active tags.

**Comment by lucyWMDE** [comment]
agree - added to the original list.
