### ISSUE TITLE
Regular headers

### ISSUE THREAD

**Issue by lucyWMDE** [codingdavinci/relaunch2018#167]
Text width should be 50%, left justified.

**Comment by lucyWMDE** [comment]
There's still some weird things going on with these headers. I realise there are 2 categories to talk about here:
1. Headers on **Einfache Seite**
eg http://codingdavinci.snater.com/en/node/905
- Titel - this could (should?) be full-width. At the moment it is set to 50% and the huge padding on the right hand side means it behaves weirdly on smaller screens
- Kurzbeschreibung - this one _should_ be 50%. Though it'd be good to not have the same right-side padding problem - also better to have the column to switch to full width at an earlier breakpoint I think.


2. Headers on special pages
eg http://codingdavinci.snater.com/en/faq 
Here you've put Titel and Kurzbeschreibung in the same 50% page width div. We have the same problem with the large right-side padding at smaller screen widths. Please reduce the right-side padding when it's at 50%. Also, I'd suggest we flip to full width at an earlier break point. I also think it would be better to take the Titel field out of this div and just use a regular full-width div for that - as we do that we should also make sure there's space between the title and Kurzbeschreibung - currently there isn't any.

**Comment by Snater** [comment]
Let's try this.
