### ISSUE TITLE
Einfache Seite: Bildunterschriften

### ISSUE THREAD

**Issue by lucyWMDE** [codingdavinci/relaunch2018#170]
image/video/gallery Unterschriften should all have same font size and position - Video Unterschrift is correct (16px, 24px margin above) - although, I have to say, I think the 24px margin looks a bit big on non-full-width images... 

Stephanie - what would you suggest?

**Comment by stffb** [comment]
Margin 12 would work.

**Comment by stephanie** [comment]
Hey sorry but I think you are tagging the wrong @stephanie in these PRs!

**Comment by lucyWMDE** [comment]
ah - my bad - sorry about that!
