### ISSUE TITLE
Einstellung question - text editor

### ISSUE THREAD

**Issue by lucyWMDE** [codingdavinci/relaunch2018#172]
Do we have a way to edit what’s available in the text editor to remove some options for some editors? (eg “Seiten-Übertitel”, “Kleine Titelüberschrift”, “Kleiner Text”)

**Comment by Snater** [comment]
Yes, we could add additional text formats and restrict specific user groups to those formats. Yet I would not try to go into huge detail here since that will become rather confusing with a couple of text formats.

**Comment by lucyWMDE** [comment]
Sounds like we would have to duplicate existing formats to make this happen... sounds complicated. If it's not possible to simply remove certain styles from the text editor, then I guess we should leave this alone. It'll mean some policing from the admins of the regional organisers... but hopefully if we give them good Musterversionen of their event pages to work from they won't play around too much.

**Comment by Snater** [comment]
It's not that complicated after all. Once the site is back online, you can take a a look at `Konfiguration > (Inhaltserstellung) Textformate und -editoren`—there are are three default formats and we could add additional ones or just adjust the existing ones. Each format can be assigned to multiple user groups.

**Comment by lucyWMDE** [comment]
great - I've taken a look and (hopefully) straightened out the available styles for different users. Thanks!
