### ISSUE TITLE
Einfache Seite: Box/Box-Gruppen images

### ISSUE THREAD

**Issue by lucyWMDE** [codingdavinci/relaunch2018#173]
Good that we have standardised image dimensions, but we have to do it without stretching the images - [see here](http://codingdavinci.snater.com/de/was-ist-coding-da-vinci), the quotes section: what happens if we want to use Hochformat images? 

If this is all rather complicated to implement technically we can always resolve it in the workflow. Let me know what you think is the best solution.

**Comment by Snater** [comment]
Yes, that stretching is silly of course. I applied an improper scaling method to the image style.

Now, scaling and cropping is applied to achieve the exact dimensions. But this might also not be what you want. Cropping is applied towards the center of the image (could be changed to any direction), we could also apply manual cropping like it is done on the project images, but this would make things a bit more complex for editors.

I mean, I don't know. The images used in Figma do all have that format, so I assumed you would always be using that format here… I can assign whatever format and we do not even need to specify an exact dimension. Only specifying the width would be enough, for example. That would result in using every image in its original format / aspect ratio.

**Comment by lucyWMDE** [comment]
I'll have a look at what you've implemented. I think this might be the cleanest solution. Images can be manually cropped and reuploaded if the automatic crop isn't suitable. Querformat it is! I think that's fine for these boxes.

**Comment by lucyWMDE** [comment]
Content dev has gone well so far with this set up so we'll just leave this like it is.
