### ISSUE TITLE
Einfache Seiten: Box/Box-Gruppen background colours

### ISSUE THREAD

**Issue by lucyWMDE** [codingdavinci/relaunch2018#174]
Stephanie's suggestion outlined in figma is to restrict the use of box background colours to white (maybe also the pink of the menu?) plus on event pages one/both regional colours. 
Stephanie: is that right?
@Snater: Is it possible to restrict colours like that on specific pages?

**Comment by stffb** [comment]
Right

**Comment by Snater** [comment]
The colors are already restricted through the corresponding taxonomy. I don't think it's impossible, but adding the regional colours could be a little bit tricky.

**Comment by lucyWMDE** [comment]
ok - don't spend a lot of time on it. If it's too tricky to restrict to regional colours we'll just go with page background (F5F5F5) and the menu colour (FCD9C8).

**Comment by Snater** [comment]
OK, the colours should be limited with the next update. This is just a change in the `Hintergrundfarben` taxonomy, so no commit here.

Just dropping in some explanation here: Using the regional colours would be tricky as it would kind of break the data model boundaries. We would need to inject the information from a parent component. At the moment, the information is not defined in a parent component, but in the same component (the `Event` instance). So, defining the colour scheme on the `Event` instance together with specifying box paragraph background colours does not work properly.

If we had, for example, something like a `Region` content type which we would create an instance of for every region and each `Event` content type instance would reference a `Region` instance, we could bind a regional colour scheme to a region an inject that into the `Event` instance. That would be a clean solution, but I am sceptical it's worth blowing up the data model just for the purpose of being able to select specific regional colours in the box paragrahs.

**Comment by lucyWMDE** [comment]
agree. Thanks for the explanation :)
(Realised one of the colours I'd given you for the background colours was wrong (hellgrau should have been white `#FFF` - I've changed it in the taxonomy.)
