### ISSUE TITLE
Tag styles logic

### ISSUE THREAD

**Issue by lucyWMDE** [codingdavinci/relaunch2018#178]
Relevant for:
- [News](http://codingdavinci.snater.com/de/news)
- [Projekte](http://codingdavinci.snater.com/de/projekte)
- [Daten](codingdavinci.snater.com/de/daten)

There are some discrepancies in the way the tag styles logic has been implemented, both in filter controls and in tags displayed on teasers and articles. I think it would make most sense if @stffb goes through this and gives feedback directly.

**Comment by stffb** [comment]
Project and Data — it makes sense to me. Perhaps we can change the »x« less bold?
News — would use the same logic just without the »x«. So selected is also filled dark green.

**Comment by lucyWMDE** [comment]
Closing after talking to Stephanie - issue is not as big as I thought. Outstanding problem is described in #190
