### ISSUE TITLE
News Article: Additional paragraph types

### ISSUE THREAD

**Issue by lucyWMDE** [codingdavinci/relaunch2018#179]
It would be good to have additional options for adding images to news articles - It's not always easy to find appropriate full-width images. Would it be possible to easily add "textblock links/rechts" and/or "Bildergalerie" paragraph styles to the article page-type?

**Comment by lucyWMDE** [comment]
Duplicate of #95

**Comment by Snater** [comment]
Yes, that should be possible. I will try to add those three paragraph types.
