### ISSUE TITLE
Single project page: prize label

### ISSUE THREAD

**Issue by lucyWMDE** [codingdavinci/relaunch2018#185]
- prizes won should no longer appear as tags in the tag list at the top of the page. Please remove.
- Instead, we use a blue label top right over the project image in the header - see figma - there's a problem with the implementation... this space is not to be used for the Bildunterschrift. We need a different solution for that (see #181)  
- @stffb what happens if a project wins 2 prizes? Comma-separated in the same blue box?

**Comment by stffb** [comment]
»what happens if a project wins 2 prizes? Comma-separated in the same blue box?«
Ah…didn't thought of that…I would say yes.

**Comment by Snater** [comment]
Just checked that the prize appears in the blue label now. Should be fixed along #181 .
