### ISSUE TITLE
Single event page: Jury

### ISSUE THREAD

**Issue by lucyWMDE** [codingdavinci/relaunch2018#188]
Width of jury member text box wider than in figma. I assume that’s because they’re set to 4-column width. Are we ok with that? Should the photo be a bit wider to compensate?

**Comment by stffb** [comment]
Yes. That could be a solution.

**Comment by lucyWMDE** [comment]
after discussion with @stffb we agree that there should be certain consistencies for both Jury and Preisträger sections:
- text boxes should always have a fixed width, equal to that of the image, so that... 
- the offset of image and text box causes the left image overhang and right text overhang to be the same width - as in figma 
![image](https://user-images.githubusercontent.com/42772674/74357870-d91f7b00-4dc0-11ea-8426-ad59f9865801.png)

So, in this case we need to increase the size of the image.
