### ISSUE TITLE
General: Editing

### ISSUE THREAD

**Issue by samu-wmde** [codingdavinci/relaunch2018#19]
User Stories
As a regional organiser or founder (see personas for technical skill level) I want it to be quick and easy to develop website content so that I can do it myself without needing to ask a developer.

As a founder I want the CdV website content to be as openly available as possible so that our data can be reused and we can set a good example as an open project.

As a founder I want to be able to review content from the regional organisers before it goes live so that I can make sure it is appropriate.

As a regional organiser I want to be able to get approval for my content from the founders quickly and easily so that I my content can go live asap.

Design: 
We want to include visual and graphical material in the content from the regional teams… might be best to develop templates that can be adapted

Dev: 
Preference for user-friendly CMS-like editing (WYSIWYG editor if possible). BUT not at the expense of potential to use (html coded) graphical content within pages… 

Editing templated content with a live preview would work. 

Flexible content solution with custom templated content blocks/paragraphs would be great.

**Comment by samu-wmde** [comment]
2 sprachigkeit in the backend

**Comment by Snater** [comment]
This issue appears to be rather general and is more or less a pointer onto using a CMS, which we do. Particular features should be and are addressed by individual tickets, e.g. content moderation is at #28. I just checked language switching: Switching the language using the language switcher will switch the backend language as well, but there is also #16 particularly for language switching.
I guess this ticket can be closed.
