### ISSUE TITLE
news filter weirdness

### ISSUE THREAD

**Issue by lucyWMDE** [codingdavinci/relaunch2018#193]
Applying a tag filter in the news overview page does something weird to the header 
- the page title "News" font size shrinks and becomes a link. The size change certainly shouldn't be happening... I can see that adding a link gives the option to unfilter the page... I understand the need, but I don't think this is the way to do it. I'd rather keep all filter/unfilter action in the region of the filter control tags. We can either add an "All" tag to unfilter, or use the version of the "tag selected" style that includes the "x".
- a new title appears in the header with the name of the chosen tag. I'd argue that if the "tag selected" style is implemented properly we don't need any other kind of heading. Pls remove.

**Comment by Snater** [comment]
I can remove the chosen tag name, but that might have a negative SEO impact. In regards to SEO, the `<h1>` should be the chosen tag name.

**Comment by lucyWMDE** [comment]
hmm. I think the weirdest part of the weirdness is that the "News" page title shrinks and seems to get demoted - I assume it starts out as <h1>. Is there another way to deal with this? Like, can we change the page title to "News: tag" and make it all <h1>? 
If this is a generic problem, how do other sites deal with it?

**Comment by Snater** [comment]
There's just a style difference. The concept of the header was not optimal. Yes, I could just leave out the separate "News" header and put it as a prefix in front of the tag name, so both would be in the h1 tag.

**Comment by lucyWMDE** [comment]
this looks ok now that the header styles have been improved. Closing.
