### ISSUE TITLE
401 Error for site.webmanifest

### ISSUE THREAD

**Issue by mbuechner** [codingdavinci/relaunch2018#198]
Possible solution: https://www.drupal.org/project/responsive_favicons/issues/3095438

And, this file  doesn't seem to exist!?

**Comment by Snater** [comment]
I had noticed it was not loading correctly but never got to caring about it. Yet it seems to load for me now anyway,

File does exist here: https://github.com/codingdavinci/relaunch2018/blob/master/web/site.webmanifest

**Comment by Snater** [comment]
I do receive the error now on the test deployment, only in Chrome as it appears. Fix might be https://www.drupal.org/project/responsive_favicons/issues/3095438

**Comment by lucyWMDE** [comment]
@mbuechner are we good here? Problem solved? If so, please close this issue. Thx.

**Comment by mbuechner** [comment]
👌
