### ISSUE TITLE
Events overview page 

### ISSUE THREAD

**Issue by samu-wmde** [codingdavinci/relaunch2018#2]
As a founder I want to show an overview of all the past and upcoming CdV events so that I can represent the scale of the project.

As a regional organiser of a past event I want a record of my event to be archived on the site so that I show what we achieved to prospective supporters of the next edition.

@gitstief 
Files with basic info (where, when) to represent each event - if possible written in html rather than uploaded as graphic files. Organised into sections on the page: 
upcoming/ongoing events 
archived events

**Comment by lohengruen** [comment]
Wireframe
https://www.figma.com/file/IizS2K9BPwpGnVf7nvbxQvoQ/EventsOverview-Wireframe?node-id=1%3A19

**Comment by Snater** [comment]
@lohengruen, @lucyWMDE : Is the graphical concept finished on that (the appearance of the boxes)? We don't have data sets we can pull images from yet and no regional logos yet. That one (https://www.figma.com/file/lLxLCHZL95ReAyDSwQ97ok/EventsOverview-Boxes-Design) is to be implemented, right? 

I'd like to postpone that issue to wait for having all things regarding events together, as filtering the events into two lists for upcoming and past events is trivial. Applying the graphics might be the more challenging part.

**Comment by lucyWMDE** [comment]
The images representing each event are placeholders for now. Happy to push this one down the list.

**Comment by Snater** [comment]
As discussed, I'll implement the logos in a simplified way and will close this ticket on that.
May be adapted as soon as regional identity has passed approval.

**Comment by Snater** [comment]
Events overview page is in place.
