### ISSUE TITLE
Hosting the Website

### ISSUE THREAD

**Issue by samu-workopen** [codingdavinci/relaunch2018#20]
@codingdavinci/guitarhero

**Comment by samu-wmde** [comment]
- User Dependency
- Staging Area 
- Hosting

**Comment by Snater** [comment]
Regarding the hosting environment: https://www.drupal.org/docs/8/system-requirements - nothing special there. Basically, PHP and MySQL. I recommend running PHP 7.2 as I will also develop on that version. Though not required, it would be very good to have SSH access, as updating the site would be a lot easier. As discussed, for the time being, I will host the dev version on my web space.

**Comment by mbuechner** [comment]
Hosting issue is solved. See https://test.codingdavinci.de/
