### ISSUE TITLE
Seitenabschnitt Preise - unable to edit/translate paragraph title 

### ISSUE THREAD

**Issue by lucyWMDE** [codingdavinci/relaunch2018#206]
Don't think we have access to edit or translate the title of this paragraph type. Currently it uses the English "Prizes" in the front end. We can access and edit the labels for what looks to be the paragraph title, but in reality this field is ausgeblendet and the real title seems to be inaccessible.

**Comment by Snater** [comment]
Translating things is really scattered… `Prizes` is a string used in a template. Hence it's translation is to be done at `/admin/config/regional/translate`. Be sure to search for the exact string (search is case-sensitive). I just verified that the string is translatable and translated it to German.
Technically, it's easier to have the string in a template—I would assume it's also not translated that often, so it made sense to me to put it there. Theoretically, the string could also be part of the paragraph.
