### ISSUE TITLE
Abschnitt Zeitleiste- Fußzeile text align bottom

### ISSUE THREAD

**Issue by lucyWMDE** [codingdavinci/relaunch2018#209]
The Fußzeile text is aligning top when it should align bottom, as it does for Abschnitt Box/Box-Gruppen. Plx fix, ty!

see here for examples: http://codingdavinci.snater.com/de/einfache-seite-titel

**Comment by Snater** [comment]
That was hard to guess by the timelines in the design having all equal heights. :D

**Comment by lucyWMDE** [comment]
fair point :)
