### ISSUE TITLE
News teasers - strip formatting?

### ISSUE THREAD

**Issue by lucyWMDE** [codingdavinci/relaunch2018#210]
Would it be easily possible to strip formatting from the news teaser texts? There's a tendency for editors to create a kind of subhead/lede paragraph in bold at the top of the article... it looks good there, but it doesn't look good in bold in the teaser. 
eg http://codingdavinci.snater.com/de/node/1771

**Comment by Snater** [comment]
It's not super straight forward, but it should be possible. Need to preprocess the node and detect whether it's supposed to be displayed as a teaser. If so, strip the tag from the text field of the text paragraph.

**Comment by lucyWMDE** [comment]
ok. will doublecheck priority for this with the Geschäftstelle.

**Comment by lucyWMDE** [comment]
They say not high enough priority to implement at this stage - content development workarounds are possible. So we can scrap this one. Thx!
