### ISSUE TITLE
News feed on news overview page and landing page - translations

### ISSUE THREAD

**Issue by lucyWMDE** [codingdavinci/relaunch2018#211]
We should only see one language version of a news article in the news feed on the landing page and news overview page: either the appropriate translation if it exists, or whatever else is available (if we have to choose a default/priority, it would be German). Currently we're displaying all language versions in the feed.

We also see the 2 language versions listed as 2 separate articles in the [content list](http://codingdavinci.snater.com/en/admin/content).

This is similar to #212

**Comment by lucyWMDE** [comment]
Fixed for the News feed here http://codingdavinci.snater.com/de/news, but the short news feed at the bottom of the landing page still shows both language versions of a single article.

**Comment by Snater** [comment]
Didn't remember that was on another view. Should work now.
