### ISSUE TITLE
Landing Page: "block-figures" graphic

### ISSUE THREAD

**Issue by lucyWMDE** [codingdavinci/relaunch2018#214]
"x Institutions, x Data sets, x Projects"
If the text here can only be in one language, we'd like to use German.
"Institutionen, Datensets, Projekte"
If it's possible to use multiple languages that'd be great, but I couldn't figure out how to access the text through drupal, let alone translate it.

**Comment by Snater** [comment]
Just checked: It should be translatable through the interface translation which is at http://codingdavinci.snater.com/de/admin/config/regional/translate

**Comment by lucyWMDE** [comment]
oh wow that worked :) It's a bit mysterious to me, but if it works it's all great :)
