### ISSUE TITLE
Landing page: header subtitle "Coding da Vinci ist ein Kultur-Hackathon..."

### ISSUE THREAD

**Issue by lucyWMDE** [codingdavinci/relaunch2018#215]
Don't seem to be able to edit the subtitle at the very top of the landing page
![image](https://user-images.githubusercontent.com/42772674/82460449-745b7700-9ab9-11ea-9256-0fa10b70a357.png)
Is this an image?
We would like the text to read "Coding da Vinci ist der erste deutsche Hackathon für offene Kulturdaten. Hier entfalten innovative Anwendungen das kreative Potential in unserem digitalen Kulturerbe."
Will it be possible for us to edit and translate this content? Or is that not on the cards...?

**Comment by Snater** [comment]
It's a custom block that can be edited at http://localhost/codingdavinci.de/codingdavinci.de/web/de/block/14?destination=/codingdavinci.de/codingdavinci.de/web/de/admin/structure/block/block-content

Struktur > Blocklayout > Bibliothek benutzerdefinierter Blöcke > Startseite: Unteritel

(It's placed in "Kopfzeile" on Struktur > Blocklayout)
