### ISSUE TITLE
redirect links

### ISSUE THREAD

**Issue by lucyWMDE** [codingdavinci/relaunch2018#218]
I must have asked this before but I guess we postponed it. How can I set redirect links so that visitors with urls from the old website end up at the right place.
True for 
- all projects
- all events
- some basic pages like "about us", "Stipendien", "Presse" just in case. 

e.g.
https://codingdavinci.de/projects/2019_west/sounds_without_meaning.html
->
http://codingdavinci.snater.com/de/projekte/sounds-without-meaning

**Comment by Snater** [comment]
You can create path aliases at `/admin/config/search/path` (Konfiguration > Suche und Metadaten: URL-Aliase). Aliases at least for the projects were already created when importing, so you can already access project aliases like http://codingdavinci.snater.com/projects/2015/wiederaufbau-ost-berlin.html. But I guess you need to manually add all projects that have been added after the import.
