### ISSUE TITLE
Problem with translating projects and datasets

### ISSUE THREAD

**Issue by lucyWMDE** [codingdavinci/relaunch2018#219]
Unable to save translations (French and English) of projects or datasets. Creation in default German is no problem. Attempting to save a translation gives following error message:
![image](https://user-images.githubusercontent.com/42772674/83031883-6ff10a00-a035-11ea-8bf6-e7735c4c8161.png)

**Comment by lucyWMDE** [comment]
_Creating_ dataset in a different default language (English or French) IS possible... but I get the same error message if I try to create and save a German translation.

**Comment by Snater** [comment]
There was some misconfiguration in this super complex content language setup.

With the untranslatable fields being hidden, the pages to translate content look not super nice with missing padding etc. If that should be changed, let's do it on another ticket.

**Comment by lucyWMDE** [comment]
thanks - I'm not sure I understand what the issue is with the padding - looks good enough to me... 
but with translations in place it shows we also have an issue with not being able to toggle the language switch to see those translations... see new issues #230 and #231
