### ISSUE TITLE
Create page footer

### ISSUE THREAD

**Issue by lucyWMDE** [codingdavinci/relaunch2018#22]
As a founder I want to include the logos of the founders and funder in the footer so that they are visible in the project.

Precise order of logos and Förderformel has already been defined.

**Comment by lucyWMDE** [comment]
@lohengruen these are the (provisional) formulations we'll need to use: 

// Until end 2018

"Coding da Vinci - Der Kultur-Hackathon ist ein Projekt der Deutschen Digitalen Bibliothek, dem Forschungs- und Kompetenzzentrum Digitalisierung Berlin (digiS), der Open Knowledge Foundation Deutschland und Wikimedia Deutschland."

[DDB logo], [digiS logo], [OKF logo], [WMDE logo]


// From Jan 2019

"Coding da Vinci - Der Kultur-Hackathon ist ein Projekt der Deutschen Digitalen Bibliothek, dem Forschungs- und Kompetenzzentrum Digitalisierung Berlin (digiS), der Open Knowledge Foundation Deutschland und Wikimedia Deutschland in Zusammenarbeit mit und gefördert von der Kulturstiftung des Bundes."

[DDB logo], [digiS logo], [OKF logo], [WMDE logo], [KSB logo]

**Comment by lucyWMDE** [comment]
@lohengruen do you think the logos might be too small in the mobile version..?

**Comment by lohengruen** [comment]
It's probably best if the logos in the footer fold on top of each other in the mobile version. 

see here:
https://www.figma.com/file/SuZXERKieUwNQSmy6fldrFNi/Mobile-Version?node-id=0%3A1

**Comment by Snater** [comment]
OK, done. I will update the staging tomorrow evening latest, so we can have look at the current state on Wednesday together and correct implementation can be verified.
Just reopen if something's missing or create new issue tickets.
