### ISSUE TITLE
Problems with changing published status of event pages

### ISSUE THREAD

**Issue by lucyWMDE** [codingdavinci/relaunch2018#221]
**admin user** can unpublish a previously published event then make and save edits. However unable to re-publish the event - this is not offered as an option. Admin needs to be able to re-publish the event.

Currently **event team user** is unable to unpublish a previously-published event to which they have been assigned (only admin can do that) and is also blocked from accessing or editing unpublished their event. Event team should be able to unpublish, access, edit, save, and re-publish their event.

**Comment by Snater** [comment]
I extended the permissions of the event team role.

Clarification: Event team is now also able to publish an event. If they only should be allowed to re-published an event that was unpublished before, this would involve some more implications -> new issue.

**Comment by lucyWMDE** [comment]
great as it is. I made a new issue #236 to ask how we could adjust this ourselves in the future should the Geschäftstelle need to exercise more oversight over the event teams.
