### ISSUE TITLE
Register new institution user - no email confirmation recieved

### ISSUE THREAD

**Issue by lucyWMDE** [codingdavinci/relaunch2018#224]
When a new institution registers via http://codingdavinci.snater.com/de/user/register?role=institution the user account is created, but the institution does not receive an email with a link to confirm the registration and create a password.

**Comment by lucyWMDE** [comment]
N.B. this is not a case of being impatient. User registration emails are sent and received when registering as a project team via http://codingdavinci.snater.com/de/user/register

**Comment by Snater** [comment]
I tested this locally but could not reproduce. There is no difference in the user registration process. The native registration process is used for both roles. Assigning the role is actually done immediately after the registration has been processed by adding a handler that is processed after the native user registration.

**Comment by lucyWMDE** [comment]
sorry - agree. We must have made a mistake when testing. Thanks..!
