### ISSUE TITLE
Event team rights - should be able to unpublish, edit, save as draft and republish datasets and projects

### ISSUE THREAD

**Issue by lucyWMDE** [codingdavinci/relaunch2018#225]
Event team users should be able to fully manage all datasets and projects submitted to their event, including ability to unpublish previously published datasets and projects, then edit, save as draft, and eventually re-publish them.

**Comment by Snater** [comment]
There were some permission missing that had been added at some point. If some permissions are still missing, please let me know what's not working specifically.
