### ISSUE TITLE
Submission Redaktionskette - Datasets and Projects

### ISSUE THREAD

**Issue by lucyWMDE** [codingdavinci/relaunch2018#227]
Currently the steps for institution and project team users to submit/correct/withdraw datasets and projects are a little different from each other. I've listed the things to change at the bottom of this issue... but for background, both submission processes should be as follows:

**Submission**
- user registers
- [optional] user creates dataset/project and enters content, saves as "Entwurf"
- user finalises dataset/project content, ändern in "freigegeben" -> triggers email notification to event team*
- [optional] event team checks and makes edits, save as "freigegeben" (if major edits are required, event team will contact user to discuss*)
- event team finalises the dataset/project, ändern in "veröffentlicht"

**Correcting an error in a published submission**
- [optional] user logs in and edits their submission, ändern in "Entwurf"
- user finalises edits, ändern in "freigegeben" -> triggers email notification to event team*
- [optional] event team adjusts edits, ändern in "freigegeben" (if major problems with the correction event team will contact user to discuss*)
- event team approves the edits, ändern in "veröffentlicht"  

**withdrawing a submission** (problems with this step are documented in issues #225 and #226)
- event team, ändern in "unveröffentlicht"
- user and event team should still have access to edit and save as Entwurf or Freigegeben as during submission process.

-----------------------------------------------

*Things to change:
1. ändern in "freigegeben" should trigger email notification to event team users - currently this is set up for project submission but not for dataset submission - please enable for both
2. during project submission process currently some fields (at least the Beschreibung) are blocked from the project team after they save as "Freigegeben" and the event team has made an edit in that field. see here ->
<img width="1227" alt="Screen Shot 2020-05-29 at 3 15 53 PM" src="https://user-images.githubusercontent.com/42772674/83280464-fbee6780-a1d6-11ea-9280-16d7d1057f31.png">
There is no need to do this. We think it would be better (build trust) to leave the field accessible to the submitter throughout the editorial process rather than block them.

**Comment by Snater** [comment]
So I just read the things below the horizontal rule… I am unable to reproduce. "Freigegeben" which is now "request review" triggers a mail for data set submission for me. Maybe it only happens on a particular state transition? Could you try to reproduce the exact steps?

Also the Beschreibung for projects is not disabled for me after submitting and making changes to it with admin which should be the same than for event team. Also here, can you exactly retrace the steps? I assume the text format on the field was changed somehow—which of course should not happen. Event team may use Einfaches HTML and Eingeschränktes HTML while project team may only use Eingeschränktes HTML. If the text format on the field somehow flips to Einfaches HTML, project team is not allowed to edit anymore. But, as written, the text format should not magically change when editing the content of a field.

**Comment by lucyWMDE** [comment]
ok. We'll take another look and get back to you.

**Comment by lucyWMDE** [comment]
cool. the trick with the html seems to have fixed this. Can no longer reproduce. The email notification problem must have been an oversight/slow email account or something. All good danke :)
