### ISSUE TITLE
Edit to project submission notification email text

### ISSUE THREAD

**Issue by lucyWMDE** [codingdavinci/relaunch2018#228]
<img width="1419" alt="Screen Shot 2020-05-29 at 3 28 48 PM" src="https://user-images.githubusercontent.com/42772674/83280614-38ba5e80-a1d7-11ea-9c47-d97fa610573b.png">
This text should read "...Das verantwortliche Event team..."

**Comment by Snater** [comment]
This can be changed in the interface translation at `/admin/config/regional/translate`. I changed it and it will be available on the staging.
