### ISSUE TITLE
We need an overview of content moderation status

### ISSUE THREAD

**Issue by lucyWMDE** [codingdavinci/relaunch2018#229]
We need a way to see from Verwalten>Content which things are pending review and have unpublished revisions. Just Published/unpublished is really not good enough. I've been trying to read up on drupal's content moderation options and figure out what you implemented for us so that we can save as "Entwurf" and "Freigegeben". I found this article...
https://www.acquia.com/blog/workflows-drupal-8-content-revisions-and-moderation
![image](https://user-images.githubusercontent.com/42772674/83283757-ff382200-a1db-11ea-808a-af29b0f89d3d.png)
looks smart :)

Perhaps you worked with the content moderation module? Maybe you customised the module anyway so that we could include the "Freigegeben" state as a way to notify the event team that a draft is finished and ready for review... is that right? I don't see anything in that article that implies there's a smarter way to automate the notificatiions. So... we were thinking "request review" would be a better term than "Freigegeben" - assuming we keep this system could you change it for us?

Is there a way we could be using the Verwalten>Content>Content Moderation tab to list content waiting for review? Right now it doesn't seem to be implemented like that. eg http://codingdavinci.snater.com/de/projekte/cool-visualization-project-edit dataset has an unpublished revision but doesn't show up in the list.

**Comment by Snater** [comment]
The view used on the content moderation tab was broken, obviously because of the sincere customisations we applied. :)
Changed the label of "Freigegeben" to "request review" as requested.
