### ISSUE TITLE
language switch single dataset or project

### ISSUE THREAD

**Issue by lucyWMDE** [codingdavinci/relaunch2018#231]
The language switching controls top right of the screen don't seem to be active for single dataset pages, eg
- http://codingdavinci.snater.com/de/daten/atlas-der-grenzen-zwischen-frankreich-und-preussen-1833 - has a French translation but there's no way to access it.
- http://codingdavinci.snater.com/de/projekte/sounds-without-meaning has an English version, but I can only access it by editing the url... and then only because the title is the same in English and German.

**Comment by Snater** [comment]
Unable to reproduce. Works for me locally and on staging. The styling of the language switcher is not optimal but I will fix that on another issue. For the first example, the "Fr" link is clickable and leads to the French version, for the second example, English.

I just thought what could be related is that I cleared the Drupal caches before exporting the database to continue developing locally. But the language switcher is not supposed to be cached on the other hand. The function altering the language switcher runs on every render. So I am not sure what has caused this behaviour. Reopen if it still exists.

**Comment by lucyWMDE** [comment]
Agree - for both of those links I could also make the switch from German to other language... but then I couldn't switch back. Unsure what's going on there. This seems to be true for all datasets - now we can't switch from other language back to German. True for these at least: http://codingdavinci.snater.com/fr/daten?event%5B0%5D=1770

**Comment by lucyWMDE** [comment]
awesome!
