### ISSUE TITLE
registration form titles

### ISSUE THREAD

**Issue by lucyWMDE** [codingdavinci/relaunch2018#234]
following up from issue #216 

> > > > http://codingdavinci.snater.com/de/user/register to register project teams
> > > > http://codingdavinci.snater.com/de/user/register?role=institution to register institutions
> > > > Is it possible to add some text to differentiate between the two registration forms? eg edit page title to "Neues Benutzerkonto erstellen: Project Team" and "Neues Benutzerkonto erstellen: Institution"
> > > 
> > > The page titles are already translatable per interface translation: Current strings are "Create new institution account" and "Create new participant account". If those shall be different, please create a new issue.
> > 
> > Cool - those titles would be great... but I see now both pages have the "Create new institution account" title. The "Create new participant account" title has been overwritten.
> 
> Not the case for me, might also just be related to caching.

I still see the problem - there's only 1 title for both pages, "Create new institution account". I've tried clearing the cache and used multiple browsers on several devices.

**Comment by lucyWMDE** [comment]
so weird. Today there's still only one title for both pages but it's "Create new participant account". I've cleared the cache I don't know how many times but it always comes up the same.

**Comment by Snater** [comment]
Also seems to be some caching. The change seems to solve it.

**Comment by lucyWMDE** [comment]
yep - seems fine now. thx
