### ISSUE TITLE
how do we manage rights for different usergroups and content-types?

### ISSUE THREAD

**Issue by lucyWMDE** [codingdavinci/relaunch2018#236]
Hi Henning,
Rights for the various usergroups seem to be fine as they are right now... But we can imagine scenarios where we might want to change them in the future depending how things go.
- we might want event teams to require approval from admin to publish (changes to) their event page or the datasets/projects submitted to their event.
- we might want to allow institutions or project teams to be able to un-publish their own submissions.
- we might want to enable event teams to edit Presse-mappen

Can you give us a brief description of how we would make these changes ourselves? thx

**Comment by Snater** [comment]
What you want to look at is `/admin/people/permissions` (Benutzer > Berechtigungen). In the section "Content Moderation" you can assign permissions on whether roles are allowed to perform certain content moderation state transitions as defined per `/admin/config/workflow/workflows`.

For the first bullet point, you would for example remove the permission "Der Arbeitsablauf Datensatz verwendet folgenden Änderungsvorgang: Publish" and "Der Arbeitsablauf Veranstaltung verwendet folgenden Änderungsvorgang: Publish" from Event Team.

For the second bullet point, you would enable "Der Arbeitsablauf Projekt verwendet folgenden Änderungsvorgang: Unpublish" for Project team and similar for insitution.

For the third bullet point, you would assign permissions to create and edit "Pressemappe" nodes in the section "Node".

That should be all there's to it.
