### ISSUE TITLE
Enable translation for Abschnitt "Überschrift"

### ISSUE THREAD

**Issue by lucyWMDE** [codingdavinci/relaunch2018#238]
![image](https://user-images.githubusercontent.com/42772674/88158251-190a4a00-cc0c-11ea-9cf7-13a5ca58c410.png)
I'm unable to translate the heading "Was ist Coding da Vinci?" on the landing page. 
Also unable to translate Headings on the CdV Saar-Lor-Lux event page.

Seems to be because Seitenabschnitt "Überschrift" is not set to be translatable. 
http://codingdavinci.snater.com/en/admin/structure/paragraphs_type/heading

I've tried to enable translation on [this page](http://codingdavinci.snater.com/en/admin/config/regional/content-language), but when I try to save I get this error message...
![image](https://user-images.githubusercontent.com/42772674/88158667-9d5ccd00-cc0c-11ea-8fe4-79f0fea58f4a.png)

**Comment by Snater** [comment]
There was another check box ticked which prevented saving. I ticked that off an was able to save the page with the text of "Übersetzung" marked as translatable. I hope things work now. This translation management page is super tricky and I would actually tend to advice to not change things there unless exactly knowing what is going on there.
Especially paragraph types are special in terms of translation and one of these many checkboxes checked accidentally leads up to not being able to save translations and to find that exact checkbox might be tricky. The thing is we have a pretty complex setup with all these paragraphs.

**Comment by lucyWMDE** [comment]
ok. I hope that was the only one then. thx
