### ISSUE TITLE
Dataset overview page - sort order datasets/reorder filter categories

### ISSUE THREAD

**Issue by lucyWMDE** [codingdavinci/relaunch2018#240]
Not a blocker, but I think it was part of the original brief and I can't figure out how to do it myself. The sort order of the datasets you first encounter when you go to http://codingdavinci.snater.com/de/daten - should be datasets from the most recent event first. I tried adding all kinds of sort criteria here: http://codingdavinci.snater.com/en/admin/structure/views/view/data_sets - using event or authored-on categories, but I couldn't figure it out. Pls help :)

**Comment by Snater** [comment]
As far as I remember, also from #138, the last idea was to order by the creation date of the data set. And reading in the last message of the ticket, that could be re-enabled. Yet I do not seem to have been able to get it to work instantly. The filter mechanics are extremely complex since there is a lot of referencing. In our case, things do not work out of the box and adjusting that is an absolutely major task.

**Comment by lucyWMDE** [comment]
ok. tbh this is still on our wishlist. I wonder if there might be a way to address it by switching/upgrading databases during the migration?

**Comment by lucyWMDE** [comment]
update: this is still on our wishlist... but as it's such a tricky one we'll go ahead to launch without it ON THE CONDITION THAT we rearrange the order of the filters in the left sidebar. New order would be

- Event
- Objekttyp
- Lizenz Mediendateien
- Thema
- Institution
- Volltextsuche

I guess I can't change it in the settings. Assume it would have to be changed here and I didn't want to risk messing anything up:
https://github.com/codingdavinci/relaunch2018/blob/master/web/themes/custom/relaunch2018/templates/views/views-exposed-form--data-sets.html.twig

p.s. after resetting the Better exposed filter settings for #242 we've lost the collapsible-ness of the Objekttyp filter - both parent and child categories are automatically displayed now. We should only be able to see parent categories. Sub-categories should only be revealed when their parent category is selected.

**Comment by Snater** [comment]
Sorry, I was a waiting if there would be a turnout on #249. Now looking at this ticket, I am not sure which filters should remain in the collapsed section (mobile view), so I did not change it now.

But, indeed, you can just change the order of the filters in the file you linked.

**Comment by lucyWMDE** [comment]
ok. I made the changes and sent you a [pull request](https://github.com/codingdavinci/relaunch2018/pull/257) - not confident just editing the master like that. 
Thanks
