### ISSUE TITLE
Footer logo edit

### ISSUE THREAD

**Issue by lucyWMDE** [codingdavinci/relaunch2018#247]
We honestly didn't think we'd have to change the logos in the footer... but the KSB has made another request. Since we don't have access to edit that area (afaik) could you please swap the KSB  logo for [this one](https://www.google.com/url?q=https://drive.google.com/file/d/1u4ySJHX2OO5bT7iGGfeRc7ok0lhFige6/view?usp%3Dsharing&sa=D&ust=1597919468100000&usg=AFQjCNGhnmDOpqkrSF0M-8xq9OJP9aw7Zw) and edit the text above it from "Funded by” to “gefördert im Programm". Thanks!

**Comment by lucyWMDE** [comment]
ok. Text is done.
I tried to upload the new logo here: https://github.com/codingdavinci/relaunch2018/tree/master/web/themes/custom/relaunch2018/img/footer Seems to have overwritten the old logo. Hopefully it works and can be implemented once you have access to the test system. thx!

**Comment by lucyWMDE** [comment]
Reopening this with a question... the KSB asks if their logo can be made bigger. 
![image](https://user-images.githubusercontent.com/42772674/93481980-7dd9dc00-f8ff-11ea-99bc-7a8dbbedfd9d.png)
Is there perhaps an easy way to increase the width of the first column?

**Comment by Snater** [comment]
The column widths were just equal. I adjusted them just by eye measuring so all logos take a bit more kind of the same space in terms of area.
