### ISSUE TITLE
Speed - dataset overview pages take a LONG time to load and filter

### ISSUE THREAD

**Issue by lucyWMDE** [codingdavinci/relaunch2018#249]
I count over 20 seconds to load some filters (eg filter for "Bild", "text", any of the Thema filters) if they're not already cached. Is there anything we can do to speed it up?
Project overview pages seem to load much faster.

**Comment by mbuechner** [comment]
Can't say anything to that, except SQL query is way too long, solution three probably the best one. ;-)

**Comment by ikyriazi** [comment]
Dear @flokosiol, have you started working on this issue?

**Comment by flokosiol** [comment]
@alex-knaub and I had a closer look on this issue and he wanted to contact you – he probably already did.

**Comment by ikyriazi** [comment]
Dear @alex-knaub and @flokosiol, we are still waiting for the 3st-module regarding the improvement of loading time for our data (and project) page. A delivery before Christmas would be highly desirable. Thank you in advance!

**Comment by ikyriazi** [comment]
As of last week the issue has been resolved. Thank you all!
