### ISSUE TITLE
Draft wireframes for team

### ISSUE THREAD

**Issue by lucyWMDE** [codingdavinci/relaunch2018#25]

**Comment by lucyWMDE** [comment]
5/9: feedback to draft wireframes from @codingdavinci/guitarhero
https://www.figma.com/file/fMvBKPD5DZ2A99LgnR5RDoi7/LandingPage-Wireframe?node-id=0%3A1

- "Desktop" events/news section needs to be clarified.  Expect 1-4 upcoming events at any time
- Project section: https://github.com/codingdavinci/relaunch2018/issues/9#issuecomment-418659111
- Founders: 
- Social media:
- Call to action "Get involved" - connect with testimonials: 
- 2-sprachigkeit: 
- Menu overlay:

**Comment by Snater** [comment]
Closing since moved to Done.
