### ISSUE TITLE
Abschnitt Textblock rechts/links - can't edit

### ISSUE THREAD

**Issue by lucyWMDE** [codingdavinci/relaunch2018#250]
Very similar to the old bug #200 
Appeared since migration.
Once created we are unable to make edits to the image/video/text in
- rechte Spalte of textblock links
- linke Spalte of textblock rechts
When we try to edit, we get the error message " Nicht zu übersetzende Felder können nur durch eine Aktualisierung der aktuellen Revision geändert werden"

Doesn't seem to have anything to do with actual translations as the bug appears even when working on a page that only has original German version.

Only work around is to delete the whole Abschnitt and remake.

**Comment by Snater** [comment]
I updated the translation configuration on the test system. Please check if the error still exists. If it does, does it appear only on one or more particular media types to be used in the "opposing" column? Could you point me to a specific node (page) where the error is triggered?

**Comment by lucyWMDE** [comment]
The error's still there :/ 
I'm testing on this page: https://test.codingdavinci.de/de/einfache-seite-titel - the paragraphs at the top of the page. It's an issue for both textblock links & rechts and for every type of "opposing" column. And it gets triggered if I perform the following actions on the content of the "opposing" column:

- photo column - replace with another photo, delete photo
- video column - replace with another video, delete video
- text column - make any edit to überschrift or body text

**Comment by Snater** [comment]
Ok, reproduced, changed config again, seems to work now from what I experience.

**Comment by lucyWMDE** [comment]
yeppers! nice. THanks :)
