### ISSUE TITLE
Berichterstattung links 

### ISSUE THREAD

**Issue by lucyWMDE** [codingdavinci/relaunch2018#252]
https://test.codingdavinci.de/fr/presse
![image](https://user-images.githubusercontent.com/42772674/91033343-817d8a00-e603-11ea-9e9c-bc8523f65f12.png)
Links that should lead directly to articles instead lead to an intermediate internal page. Can we change this?

**Comment by Snater** [comment]
Go to Struktur > Ansichten > Pressemappen [Bearbeiten] and choose "Berichterstattung". Click on `Content: Title [ausgeblendet]` in `Felder`, uncheck `Link zum Content`, click `Anwenden (diese Anzeige)` and `Speichern`.

**Comment by Snater** [comment]
Just fixed on test deployment. :)
