### ISSUE TITLE
Registration email confirmation error

### ISSUE THREAD

**Issue by lucyWMDE** [codingdavinci/relaunch2018#253]
Trying to make new project team or institution accounts via the registration pages
https://test.codingdavinci.de/de/user/register
https://test.codingdavinci.de/de/user/register?role=institution
...returns this error:
![image](https://user-images.githubusercontent.com/42772674/91459494-fe6c6600-e886-11ea-9c3f-506637943c04.png)

Is there something we haven't gotten set up properly with the migration?

**Comment by mbuechner** [comment]
How's Drupal sending e-mails?

**Comment by Snater** [comment]
It's using PHP's native `mail()` as per default.

**Comment by mbuechner** [comment]
Should better be an SMTP server. I'll discuss that with Philippe and @ikyriazi

**Comment by ikyriazi** [comment]
Hello! I see that that message "no email can be sent" doesn't appear anymore, however I don't receive an email in my mailbox either. I saw also that Michael made a new release today (https://github.com/codingdavinci/relaunch2018/releases/tag/v1.0-beta7), where he added the module drupal/phpmailer_smtp.

1. @mbuechner is your question about whether we should have an SMTP server meanwhile answered?
2. I see the error "User warning: mkdir(): Permission Denied in Drupal\Component\PhpStorage\FileStorage->createDirectory() (line 145 of core/lib/Drupal/Component/PhpStorage/FileStorage.php)." on every page at the website. Is it somehow related, or is it a totally different issue?

**Comment by mbuechner** [comment]
I resolved that issue. Installed the module [SMTP](https://www.drupal.org/project/smtp), configured all to `info@codingdavinci.de`, changed website e-mail address, admin e-mail and maintenance e-mail address to this one as well.

Could you please check if everything's okay?
