### ISSUE TITLE
Bildunterschrift license commas

### ISSUE THREAD

**Issue by lucyWMDE** [codingdavinci/relaunch2018#254]
There is a problem with the way the License and Namensnennung for images is presented that I can't figure out how to fix.
See examples on [this page](https://test.codingdavinci.de/de/einfache-seite-titel) - applies to Abschnitt textblock links/rechts, gallery, and likely all image pargraphs.

![image](https://user-images.githubusercontent.com/42772674/91464918-67ef7300-e88d-11ea-8d7f-10276b712c05.png)
![image](https://user-images.githubusercontent.com/42772674/91465094-a6852d80-e88d-11ea-97f4-2766e7cb4ecf.png)

- There is a weird extra comma before the name, with or without a line-break in between. This should be removed. I guess it's safe to assume the editors will use a full-stop at the end of the caption.
- We need a space between the comma after the name and the license code. eg  "Stephan Bartholmei, CC-BY-4.0" rather than "Stephan Bartholmei,CC-BY-4.0"

**Comment by Snater** [comment]
I just checked on test deployment. Seems to be alright now. :)
