### ISSUE TITLE
Event page/Abschnitt Bild - Image sizing/resolution problem

### ISSUE THREAD

**Issue by lucyWMDE** [codingdavinci/relaunch2018#258]
It seems that, when used on event pages, Abschnitt Bild, which displays single images at full width (up to 1110px) always converts the actual image files to 540px width. This means that the full-width display is coming out pixelated even when a high resolution image file was originally uploaded. 
eg

![image](https://user-images.githubusercontent.com/42772674/94156878-e0435700-fe80-11ea-91b0-639a23722ba2.png)

Image uploaded at 1000×511px: https://test.codingdavinci.de/sites/default/files/2020-04/sprint.jpg
Used here: https://test.codingdavinci.de/de/events/sued-2019
...it's been converted to 540x276px but is being used at 1110px width, so it's coming out pixelated.

Maybe we can choose a more suitable image size?

see also #259

**Comment by Snater** [comment]
I have added a new image style `Maximale Breite (1100x*)` (https://test.codingdavinci.de/de/admin/config/media/image-styles)

Assigned that one per https://test.codingdavinci.de/de/admin/structure/media/manage/image/display to the `Default` view which is used by the event page and also to the `Vollständiger Inhalt` view used by the article (no need to render a 1600px image there when images are rendered at a max width of 1100px).

The `Default` view was using the `Default` image style, which scales images to 540px width.

I assume things could be streamlined a bit on the image media view configuration, and also the image styles that natively came with the default Drupal installation could be removed, but they also don't interfere, so things should be fine here now.
