### ISSUE TITLE
News article/Abschnitt Bild - layout 

### ISSUE THREAD

**Issue by lucyWMDE** [codingdavinci/relaunch2018#259]
I think "Abschitte Bild" as used for news articles might not have been fully styled? I'd have assumed it'd come out the same as Abschnitt Bild as used on the Event pages. 
eg https://test.codingdavinci.de/de/news/coding-da-vinci-stipendien-gehen-die-zweite-runde
The image should be centered on the page in line with text in, for example, Abschnitt text. I think that's the only issue though. Caption and spacing looks fine and the image resolution problem as described in #258 is actually totally fine here.

**Comment by Snater** [comment]
The left and right container margins were just overwritten.

**Comment by lucyWMDE** [comment]
still not fixed :/ Abschnitt Bild still justifies to the left - should be centred. Perhaps something went wrong in implementation..?

**Comment by Snater** [comment]
Sorry, I accidentally pushed the changes for this issue and #242 to your branch (https://github.com/codingdavinci/relaunch2018/compare/lucyWMDE-patch-1). I will merge that branch into master on Monday, unless you are quicker than me.

**Comment by Snater** [comment]
Merged branch. Please check again after the current master being deployed.

**Comment by lucyWMDE** [comment]
@mbuechner These changes (see comment above) are not yet evident on the site. Has everything been deployed?
