### ISSUE TITLE
Full screen designs for approval

### ISSUE THREAD

**Issue by lucyWMDE** [codingdavinci/relaunch2018#26]
- [x] screen designs to #2 #3 #4 #5 #6 and #17
- [x] send out to GT
- [ ] GT feedback
- [ ] incorporate feedback
- [ ] send single event page (#3) and key visuals to regional stakeholder
- [ ] regional stakeholder feedback
- [ ] regional stakeholder approval
- [ ] GT approval

**Comment by lucyWMDE** [comment]
@lohengruen Good. Can you give me a description of the animations it will use?
I will need to have new proposals for the regional identities before I can sent it back to the GT. I'd like to be able to do that next week... can you let me know what would be a reasonable timeframe to expect delivery?

**Comment by Snater** [comment]
After one month without update, I think we are a bit farther, but I am not sure we actually need to maintain that parallel process in here.
