### ISSUE TITLE
New Drupal security update

### ISSUE THREAD

**Issue by ikyriazi** [codingdavinci/relaunch2018#267]
Just 2 days after 8.9.9 a new critical update is required --> 8.9.10. 
(I have already clarified DNB-internally, that ticketed updates should be implemented by the external firm, aka assignees.)

**Comment by flokosiol** [comment]
As far as I can see, the `composer.json` file is already up to date: https://github.com/codingdavinci/relaunch2018/blob/master/composer.json#L32

Please run `composer update` to install the latest version on the server.

**Comment by ikyriazi** [comment]
Drupal core was updated and runs on the production system.
