### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by ikyriazi** [codingdavinci/relaunch2018#269]
Please update: 
- **Drupal core**: 8.9.10 --> 8.9.12
- **EU Cookie Compliance (GDPR Compliance)**: 8.x-1.13 --> 8.x-1.14
- **Metatag**: 8.x-1.14 --> 8.x-1.15
- **Token**: 8.x-1.7 --> 8.x-1.9
- **Twig Tweak**: 8.x-2.8 --> 8.x-2.9

**Comment by flokosiol** [comment]
I performed the update locally and will now check if everything is fine.

**Comment by flokosiol** [comment]
Everything seen to work fine locally, so the updates can be performed on the production server.

**Comment by ikyriazi** [comment]
Hi @flokosiol , there seems to be an error with the PHP composer (see: https://github.com/codingdavinci/relaunch2018/runs/1663320617). Is this something to solve on our end?

**Comment by ikyriazi** [comment]
Ok, the problem was solved. Our IT specialist informed me that it was an GitHub action problem.

**Comment by flokosiol** [comment]
Thanks for the info.

**Comment by ikyriazi** [comment]
The new updates have been deployed on the production server.
