### ISSUE TITLE
Security Update: please update Drupal version to 8.9.13

### ISSUE THREAD

**Issue by ikyriazi** [codingdavinci/relaunch2018#270]

**Comment by ikyriazi** [comment]
Or, should we update to Drupal 9? What would you suggest?

**Comment by flokosiol** [comment]
For now I would suggest to update to the latest 8.9.x version, but in the long run 9.x should be the goal. But this needs to be tested carefully. @ikyriazi

**Comment by ikyriazi** [comment]
Ok, thanks for the input! I guess you will do the testing for 9.x at some point, but not a priority for the moment. We head for 8.9.13 now.

**Comment by flokosiol** [comment]
I checked the update locally without any problems. 

To perform the update on production please run `composer update` and make sure to **clear the Drupal cache** afterwards. There should be no database updates.

**Comment by ikyriazi** [comment]
The new update runs on production.
