### ISSUE TITLE
Response by 0 search results

### ISSUE THREAD

**Issue by ikyriazi** [codingdavinci/relaunch2018#271]
Search results > When a search gives no results there should be the following message as response:
"Es sind keine den Filtereinstellungen entsprechenden Datensets vorhanden."
A similar response appears also in similar cases at https://codingdavinci.de/daten/
See for example here:
<img width="988" alt="Screen Shot 2021-01-27 at 9 48 52 AM" src="https://user-images.githubusercontent.com/2911489/106009252-6cc48700-60b8-11eb-8fcd-d1d3caf1806a.png">

**Comment by ikyriazi** [comment]
The response "Es sind keine den Filtereinstellungen entsprechenden Datensets vorhanden" applies to datasets (and it has been already applied, thank you!). 
Please use response "Es sind keine den Filtereinstellungen entsprechenden Projekte vorhanden.", when we get 0 search results in the **Projekte** page.

**Comment by pe3st** [comment]
ok, fixed in master

**Comment by ikyriazi** [comment]
Thanks a lot!
