### ISSUE TITLE
Sub-terms of object types are missing

### ISSUE THREAD

**Issue by ikyriazi** [codingdavinci/relaunch2018#274]
Facet "Objekttyp" > When I select a specific object type, I should be able to see its sub-terms (see how the facet "opens up" when you choose an object type at https://codingdavinci.de/daten/). The sub-terms should be combinable with an OR operator.

**Comment by ikyriazi** [comment]
Unfortunately, there has been no implementation of the Objekttyp sub-terms yet. In the old data page, as one would klick on text, for example, its subcategories would appear automatically, in order to choose more specifically between them. A combination of different object types should be still possible (as an OR operation).

Here the object types with their subcategories for your reference:
<img width="303" alt="text" src="https://user-images.githubusercontent.com/2911489/114189573-a0d6e680-994a-11eb-97a2-5471aff1f756.png">
<img width="416" alt="bild" src="https://user-images.githubusercontent.com/2911489/114189615-ad5b3f00-994a-11eb-85c1-e9160f4ee2a2.png">
<img width="184" alt="ton" src="https://user-images.githubusercontent.com/2911489/114189642-b6e4a700-994a-11eb-80d9-1a8ae42c54f2.png">
<img width="191" alt="video" src="https://user-images.githubusercontent.com/2911489/114189650-b9df9780-994a-11eb-9ea9-d6157e913031.png">
<img width="220" alt="software_modell" src="https://user-images.githubusercontent.com/2911489/114189662-bd731e80-994a-11eb-957b-d79f65c988bd.png">

**Comment by pe3st** [comment]
@ikyriazi ok, ist in master gepushed

**Comment by ikyriazi** [comment]
@pe3st could you make it so that when a subclass is selected by the user, then the main category is not highlighted anymore? For example, if I choose Bild > Plan, I would like to have only Plan highlighted (since I get only plans and not all picture types). Otherwise, it is confusing for the end user.

**Comment by pe3st** [comment]
@ikyriazi could you please close this issue and open "do not highlight parent selection" as a Feature-Request? This issue Solution resembles the behaviour of the previous User-Interface.

**Comment by ikyriazi** [comment]
After discussion, we are leaving for now the filter as it is. The parent selection remains highlighted, when a sub-element is also selected. Thanks @pe3st for your contribution!
