### ISSUE TITLE
Set up content moderation

### ISSUE THREAD

**Issue by Snater** [codingdavinci/relaunch2018#28]
There are 4 different user groups (apart from admin and guest): Founder, Event Manager, Participant and Institution. Recapitulating the briefing regarding the scope of content moderation (please correct if there is some mistake):

Institutions may create content for the Data Set content type, which is to be reviewed/published by an Event Manager on creation, as well as on subsequent edits. Since data sets may be used at multiple events, any Event Manager may review/publish changes to a Data Set content – this is least prone to conflicts.

Event Managers may create content for the Event content type, which is to be reviewed by some Founder on creation. Subsequent edits do not require approval.

Event Managers may create content for the (News) Article content type, which is to be reviewed by some Founder on creation. Subsequent edits do not require approval.

Participants may create content for the Project content type, which is to be reviewed by some Event Manager of the corresponding region on creation, as well as on subsequent edits.

Drupal has a practical user group setting restricting users to only edit content they created (without being allowed to edit content created by others). That setting will be used for Institutions who are only allowed to edit Data Set content they created, as well as for Participants (I think it is fair to only have one project team member maintain the project page content, otherwise we would need a whole logical system of dynamically aggregating teams).

**Comment by lucyWMDE** [comment]
This is great. 
- "I think it is fair to only have one project team member maintain the project page content, otherwise we would need a whole logical system of dynamically aggregating teams" - sure... as long as there's nothing about this set-up that would preclude institutions/participants from making a login that they share between them. It's especially an issue for institutions as we collaborate with them over the course of several years. It's very possible that we have more than one person per institution responsible for submitting/editing content (eg institution representative we worked with in 2014 gets a new Studentische Hilfskraft and gives them the task of submitting additional datasets in 2017).
- if there is any kind of notification of new dataset submission to review it would be better if it only goes to the relevant region event manager, rather than to ALL event managers. Institutions are primarily regional too, so in most cases the event manager from the relevant region will primarily be responsible for moderating content. 
- I take it we will be able to rename these user groups at a later stage if needed?

**Comment by Snater** [comment]
- I was just thinking about have the user creating a project or data set reference users in the project / data set content type. Those users would then be allowed to also edit the project / data set. Might be quite some lines of code, but the outcome would be pretty usable, I guess.
- So, shall institutions have a region assigned to them just like event managers?
- It would be good to have them named correctly from the beginning, also in terms of conversation. How shall the groups be named?

**Comment by lucyWMDE** [comment]
- whichever you think is the better solution in terms of UX, security, and ease of maintenance...
- I think yes. Institutions always sign up to a specific event (i.e. as part of a time- and region-specific campaign). BUT you are right - an institution might go on to join subsequent events in different regions... would it be possible to reassign the region for an upcoming event without loosing the information that they joined a specific event in the past (this would be important for the dataset filter)? If yes, would it be possible for an event manager to do that?
- user group names (provided this has nothing to do with authorship of news articles):
Founder > Geschäftsstelle
Event Manager > Event Team
Participant > Project Team
Institution > Institution

**Comment by Snater** [comment]
- Well, OK. I can leave it like that for now and the additional functionality can be added later, whenever there is time.
- There was some conceptual misunderstanding on my side. Yes, data sets need a reference to events. No problem. That reference would be independent from the region anyway. But getting back to the region regarding institutions. I think the concept of assigning regions to institutions is a bit problematic - I guess they would need to know which region they need to sign up for. It should be possible to get the necessary information from the event, the institution assigns its data set to when creating it. So, the rule would be: Notify all Event Team users of the region of the event an institution created a new data set for.
- OK

**Comment by lucyWMDE** [comment]
- ok
- hmm do we really need "region"? Isn't "EventX" enough? What does "region" add on top? Some future events might anyway be region-independent - e.g. with a specific thematic focus.

**Comment by Snater** [comment]
I assumed that Events are grouped by region deriving the concept from the term "Regional Organiser" in the briefing, as well as from the current page. There are two aspects of having region:

- By assigning regions to Event Team users, their admin interface could be cleaned of content not belonging to their respective region, as well as Project Team users not participating in events of that region. Region would be some kind of filter, basically preventing cluttering Event Team users' admin interface and notifications (if there will be notifications). Event Team users may have assigned more than one region.
- Additionally, it would be a container for region specifics, like the title of the region, some individual region colour etc.

I don't mind removing region, but there needs to be some clarification: Shall Event Team users be manually assigned to each single event (like suggested for Project Team users on projects)? Or shall every Event Team user have editing access to every event and every event's Project Team users (which would technically be the simplest solution)? Should it possible to filter for events by region in the front-end? Will there be specific colouring per region - or per event?

**Comment by lucyWMDE** [comment]
hmm.

EventX 
- relevant for projects: projects really only exist in relation to a specific event 
- user management: there will only ever be 1 event team per region at any one time. we do not actually know how likely it is that an event team will have repeated events / that a region will have more than one event (so far only Berlin did). Project teams belong to events. Institutions can belong to multiple events independent of region (though most will usually only belong to local events).
- Events can either be in a specific region OR about a specific theme

Region (combining multiple events over several years in the same region)
- this could theoretically be useful for the dataset filter... **BUT the data isn't clean**. E.g. we have institutions from Sweden who participated in CdV Nord, from Jena, Essen, Baden Wüttenberg who participated in Berlin 2014/15 when it was a central event, from Bad Arolsen for Berlin 2017... there will always be these exceptions.
- but it could be useful for news categories
- not really relevant for projects 
- what about possible thematic events that don't have a specific region?

I think organising primarily by event might be best. The only case where I think it'd be cool to have an overarching "Region" concept is for the news. But that's likely not essential.

to your comments...

> Event Team users may have assigned more than one region.

not true. But they may have more than one event.

> Shall Event Team users be manually assigned to each single event (like suggested for Project Team users on projects)? Or shall every Event Team user have editing access to every event and every event's Project Team users (which would technically be the simplest solution)? 

the former, if possible

> Should it possible to filter for events by region in the front-end? Will there be specific colouring per region - or per event?

as above, I think the only real use case for filtering by region is for news. Yes - key visuals should repeat if an event from a specific region or theme repeats at a later date... but I'm not sure if that is a functionality that needs to be so hard-coded.

**Comment by Snater** [comment]
This should be done, I will recheck when all content types are final.

**Comment by Snater** [comment]
I think we are fine here. Project team and institution users were alright already. I assigned additional permissions to the "Geschäftsstelle" users. For the sake of not running into information overflow, that role features a limited set of permissions in contrast to the admin role. However, "Geschäftsstelle" users still have all the power and can just simply assign themselves the admin role, if they want to.
