### ISSUE TITLE
Overview of datasets is NOT working!

### ISSUE THREAD

**Issue by ikyriazi** [codingdavinci/relaunch2018#280]
After the last update (https://github.com/codingdavinci/relaunch2018/commit/08ccb82cd0dd1cce76bb077824b9ceaaeb1f865f), the react-view for datasets is not working!
Here the respective link in the test system: https://test.codingdavinci.de/de/daten (I have updated the alias, so that /daten leads to the new overview page)
Please, get back on this as soon as possible, because of the issue urgency.

**Comment by pe3st** [comment]
fixed with https://github.com/codingdavinci/relaunch2018/commit/7c460e8c2a6d9057b9b0fea82fa2cd79beea5787 in [latest release](https://github.com/codingdavinci/relaunch2018/releases/tag/v1.6-beta6)
