### ISSUE TITLE
Starting page of search results (when another search has already taken place)

### ISSUE THREAD

**Issue by ikyriazi** [codingdavinci/relaunch2018#282]
When I am in a n-page of search results and I run a new search, the new search results will appear on their n-page and not on their first page. What I mean - example:
- I run a search and navigate through the results. I am in page 2 of the results.
- I run a new search. I retrieve page 2 of the new results and not page 1.

**Comment by pe3st** [comment]
ok, new search starts with first page in master

**Comment by ikyriazi** [comment]
@pe3st I don't see any changes.

**Comment by pe3st** [comment]
@ikyriazi i see, search is also under projects...i fixed datasets only

**Comment by ikyriazi** [comment]
Actually I checked only in datasets and it didn’t work!

**Comment by pe3st** [comment]
On Test, under Datasets?
I tried a Search with many pages, selected page 2, add another Term for example "Re", results start on page 1

**Comment by ikyriazi** [comment]
I guess, I didn't formulate the issue complete enough.
Yes, it works when I make a new full text search.
It would be nice though to have this feature also in combination with the filters. 
For example:
1. I type "bild" in the search box and go to the second page of the results
2. I try to restrict the results by choosing the event Berlin 2014. I get the "no datasets message", because it actually looks for a second page of the new results. There is though a page 1 of results with the combination of these terms/filters.

**Comment by ikyriazi** [comment]
In addition to my comment above:
I am not talking only for a new search (this has been apparently solved) but also for a refinement of the initial search (by using filters)

**Comment by pe3st** [comment]
ok, done in master

**Comment by ikyriazi** [comment]
With the current solution, if I click on the second page of results, the higlighted page number remains number 1 (although I get the results of page 2). This is misleading.

**Comment by pe3st** [comment]
ok, optimized in master

**Comment by ikyriazi** [comment]
The issue seems to be resolved. Thanks!
