### ISSUE TITLE
Projects: Typ des Projekts + Event

### ISSUE THREAD

**Issue by ikyriazi** [codingdavinci/relaunch2018#283]
In projects, one should be able to combine the two filters "Typ des Projekts" and  "Event" with an AND operator.

**Comment by pe3st** [comment]
ok, done in master

**Comment by ikyriazi** [comment]
@pe3st : The combination of filters doesn't work, as it should. If for example I choose Berlin 2014 and game, I get projects from other events, too.

**Comment by pe3st** [comment]
ok, done in master

**Comment by ikyriazi** [comment]
the issue has been fixed, thanks!
