### ISSUE TITLE
PIWIK integration

### ISSUE THREAD

**Issue by lucyWMDE** [codingdavinci/relaunch2018#30]
Details to follow...

**Comment by Snater** [comment]
This is pretty straight forward. I have added the Matomo module for Drupal. The JS code does not even need to be added manually, just the site id and the URL to the Matomo (Piwik) instance need to be specified on the module's configuration page -- simple as that. I have appended another step to the installation process for that. As the admin maintaining the Drupal installation needs to set up the Matomo instance anyway, he can just do the Matomo setup in Drupal as well, as it's just about filling out two form fields.

**Comment by lucyWMDE** [comment]
reopening so I have it on my list of tasks.

**Comment by mbuechner** [comment]
Matomo will be provided as Docker container from DNB. Accessible via https://report-t.codingdavinci.de/ (test) and https://report.codingdavinci.de/ (production). At the Moment we're waiting for an SQL database, which will be provided by DNB IT.

**Comment by Snater** [comment]
@ikyriazi : I have filled the required config fields on `/admin/config/system/matomo` (per Admin-Menu: Konfiguration > [System] Matomo Analytics) with the information you provided per mail. If I have entered something incorrect or for specific settings on the tracking, just apply settings there as needed when the site is back online.

**Comment by ikyriazi** [comment]
It works fine! On our end we have to update the link under "weitere Informationen", so that visitors get access to the cookies/data security policy (PG is working on the content of that page). I consider the issue closed.
