### ISSUE TITLE
Duplication in news history

### ISSUE THREAD

**Issue by ikyriazi** [codingdavinci/relaunch2018#302]
At the bottom of each news announcement there is a mistake in displaying news history.
The most recent announcement is displayed twice.
Could you fix it?
Example at page https://codingdavinci.de/de/news/cdvbw22-anmeldung-offen:
![Screenshot_2022-03-23 #cdvbw22 Anmeldung offen Coding da Vinci](https://user-images.githubusercontent.com/2911489/159716178-a8deeb1d-6603-463c-a618-88b27d29fb94.png)

**Comment by Flojan** [comment]
We are in and will fix the problem. Thanks for the example!

**Comment by ikyriazi** [comment]
The problem seems fixed. Thank you!
