### ISSUE TITLE
Admin cannot add new users

### ISSUE THREAD

**Issue by ikyriazi** [codingdavinci/relaunch2018#305]
The admin role cannot add new users (Benutzer hinzufügen)!
The blue button "Neues Benutzerkonto erstellen" doesn't activate!
<img width="365" alt="benutzerHinzufuegen" src="https://user-images.githubusercontent.com/2911489/162380205-a9b03913-4de9-4b43-8cc7-6cbdbe569233.png">

**Comment by Flojan** [comment]
The issue is fixed. @jschoenerstedt will call you for further details!

**Comment by ikyriazi** [comment]
Thanks a lot! Please call from Wednesday on.
