### ISSUE TITLE
alle Zoom-Fotos im News-Beitrag über CDVOst sind 404

### ISSUE THREAD

**Issue by mprove** [codingdavinci/relaunch2018#309]
https://codingdavinci.de/de/news/sechs-wochen-fuenf-preistraeger-und-unzaehlige-ideen-kultur-hackathon-coding-da-vinci-erstmals

Keines der Fotos im Beitrag kann aufgezoomt werden. Es gibt immer 404.

**Comment by ikyriazi** [comment]
The problem is not there anymore.
