### ISSUE TITLE
Update the README

### ISSUE THREAD

**Issue by lucyWMDE** [codingdavinci/relaunch2018#31]
Some basic info about setup, requirements for hosting, development... anything you think is appropriate to support hosting and maintenance.

**Comment by Snater** [comment]
These instructions should be sufficient. I don't think we need to list particular requirements other than being able to run composer and npm via an SSH shell. Webspace requires some common setup of PHP and MySQL, which can be found on [drupal.org](https://www.drupal.org/docs/8/system-requirements).

**Comment by Snater** [comment]
Note: GitHub is introducing Actions (https://github.com/features/actions), which, in the future, might make it quite easy to automate the deployment process.
