### ISSUE TITLE
Database dump / data export

### ISSUE THREAD

**Issue by alexander-winkler** [codingdavinci/relaunch2018#310]
Hallo! Is there any way to produce/obtain a database dump of the data used to generate the https://codingdavinci.de/index.php/de/daten page (and subpages with further info on single datasets)?
Thank you!

**Comment by ikyriazi** [comment]
Hello! We could provide you with a csv export containing almost all information and related links found in each dataset description. Currently we are updating some links from old hackathons, so if you need more accurate information, it would take 1-2 weeks. Would that work for you?

**Comment by alexander-winkler** [comment]
Thanks! Is it much of a hassle to produce the csv export? If not, I'd be interested in a slightly outdated export as well in order to find out if the data is suitable for my research purpose.

**Comment by ikyriazi** [comment]
No problem, I can send you a current export. To which e-mail address?
