### ISSUE TITLE
Implement "Presse" page

### ISSUE THREAD

**Issue by Snater** [codingdavinci/relaunch2018#33]
The "Presse" page will feature views on two content type: "Pressemappe" and "Berichterstattung".

**Comment by Snater** [comment]
I would implement ordering the press kits by creation date, but since the kits are not ordered in the screen design: Should it be a masonry layout (columns) or row-wise?

**Comment by lohengruen** [comment]
about the contacts: ideally the contacts would be links to a mail address (maybe include a mail icon next to the name), but on the old page it is just a name in plain text. @lucyWMDE: is it possible to provide a mail contact for each team?

about the layout: If possible I'd prefer a masonry grid layout that shows 2 columns on bigger screens and folds to one column on smaller devices. The order could be chronologically, unless WMDE prefers a articular order.

**Comment by lucyWMDE** [comment]
Yes. Email address should be linked. The old hyperlinks got lost in copy/pasting from the current site to the content development doc.

Order of Pressemappen, if this can be automated without trouble, would be teams for upcoming events (soonest first) followed by past events (most recent first). If it's complicated we can edit this by hand.

**Comment by lucyWMDE** [comment]
Preview looks generally good so far, but I think there are some line-height and padding issues with the Pressemappen - all looks a bit cramped. Did something go wrong with the CSS export?

**Comment by Snater** [comment]
Ignore anything above the press kits -- it did not receive any dedicated spacing and padding because of I am waiting for the key visuals which that content might somehow overlap with. Rest should be ok. What I noticed being a bit silly on a larger viewport width: One press kit is on the left and two are on the right. This is some edge case for the automatically calculated masonry layout as the amount of content of the first kit is larger than each of the other ones'. That's why the column layout wraps around to the next column right after the first press kit. Long story cut short, this problem will not be relevant as soon as there are more press kits on the page.

**Comment by Snater** [comment]
Styles are currently broken. Might also want some additional work on the header parallel to #5?

**Comment by Snater** [comment]
Default header is in place, but, same as on #5, I am leaving the ticket open if header is to be upgraded. (Put the lead text into the header? Use a tile--if so, a fixed one or dynamically loaded from a set?)

**Comment by Snater** [comment]
Technically done. Presse page features an extended header just like the FAQ page now.
