### ISSUE TITLE
Implement "About" page

### ISSUE THREAD

**Issue by Snater** [codingdavinci/relaunch2018#34]
@lohengruen @lucyWMDE : Is https://www.figma.com/file/xmsvph7F5fMJtx6CxgsT1f/About-Design final (except for the key visuals)? I could start implementing that as well -- might be a bit tricky to adapt that to the CMS, so it'd be a good idea to start implementing that as soon as possible.

**Comment by lucyWMDE** [comment]
There are still some parts to be added... @lohengruen - I've made notes again in figma.

**Comment by lohengruen** [comment]
https://www.figma.com/file/xmsvph7F5fMJtx6CxgsT1f/About-Design?node-id=0%3A1

Here's a update for the about page. As you can see, I'm reusing some of the event page modules that could also be used on other pages).

@lucyWMDE : The paragraph "Was sind offene Kulturdaten" is not included in the Content Development Doc. Should I delete it? I think it gives some important information.

**Comment by Snater** [comment]
That page requires implementing addition modules / paragraphs.

**Comment by Snater** [comment]
Extended the textblock left/right paragraph types and added a grid paragraph type. Technically, I think we are done here.
