### ISSUE TITLE
Basic form design

### ISSUE THREAD

**Issue by lucyWMDE** [codingdavinci/relaunch2018#35]
A basic form design that can be adapted for user login.

**Comment by lohengruen** [comment]
here is the user login form:

https://www.figma.com/file/Lb5CGZafTOJ2Uscahft6EO/Form-Design?node-id=0%3A1

If you need forms for different purposes, I would design those separately.

**Comment by Snater** [comment]
@lohengruen Thanks. We need the forms for participant and GLAM institution registration -> #29

**Comment by lohengruen** [comment]
ah ok - should I extend the design to include more information, like editor roles, addresses of institutions, upload of a logo, etc. ?

**Comment by Snater** [comment]
Personally, I'd opt for managing things beyond the basic registration (which requires email address and user name) in the backend using the admin theme. As both parties create content (participants projects, institutions data sets), we would have to design quite a lot.

**Comment by lohengruen** [comment]
yeah, that sounds reasonable and also more flexible for changes...

**Comment by Snater** [comment]
Login form styling is implemented (except for the header), registration forms feature the same style as of now. Updated staging just now.

**Comment by Snater** [comment]
I have applied some standardisation and headers on the login/registrations forms are in place.
