### ISSUE TITLE
Static page: Impressum

### ISSUE THREAD

**Issue by lucyWMDE** [codingdavinci/relaunch2018#37]
Wireframe to be adapted as screen design

**Comment by lohengruen** [comment]
Screen Design for Imprint:
https://www.figma.com/file/6uxDb99PjSydm2QkqmHit5/Impressum-Design?node-id=0%3A1

I didn't include a mobile version, since it's basically the same just with scaled don font sizes.

**Comment by Snater** [comment]
Will re-implement the basic page using paragraphs. Waiting for approval of the event page modules.

**Comment by Snater** [comment]
Reimplemented with paragraphs.
