### ISSUE TITLE
Data Set submission form

### ISSUE THREAD

**Issue by Snater** [codingdavinci/relaunch2018#39]
Proper layout and UX of data set submission form.

**Comment by Snater** [comment]
@lucyWMDE Shall institutions be allowed to pick a language for their data set submission (the language the institution is entering the information in for that data set, not the language of the data itself)--or is that always supposed to be German? (Note: The content translation capability would remain for users with appropriate rights, the field would just be inaccessible and invisible to institutional users, so this could be changed later on.)

**Comment by lucyWMDE** [comment]
good point. Yes - we need the possibility for institutions to submit alternative language versions of dataset information. I hope there's an easy way to implement that in the submission form. I guess it wouldn't apply to all fields (those where we have a controlled vocabulary, url fields, filetypes)... but I guess keywords could be tricky...

**Comment by Snater** [comment]
@lucyWMDE How many characters should be allowed on the description field?

**Comment by Snater** [comment]
That's done as well, specific issues should be addressed with individual tickets.

**Comment by lucyWMDE** [comment]
cool - I'd like to test these if possible. Do we have test logins for the different user-types?
