### ISSUE TITLE
Data Set filtering

### ISSUE THREAD

**Issue by Snater** [codingdavinci/relaunch2018#43]
Implement view with filter controls.

**Comment by Snater** [comment]
This is an awesome change. Took a few hours to check on eventualities, but filtering seems to work as expected. In fact, all the filtering of data sets including all relations (which are a bit complex) can "just" be clicked together in our case--except for listing the events and the institution names which requires a custom coded extra step. Even the facet filtering seems to behave as specified as we simply make use of the hierarchical taxonomy vocabulary.

**Comment by Snater** [comment]
Shaping the output took quite a while, but the project archive is generally done, including styling. The only thing missing is the lead text integration / header, for which I'd like to wait for final design results on work package A.

**Comment by Snater** [comment]
Seemed to nice to be true. While running into odd behaviour while setting up pagination, I had to spend another four hours for a dozen of lines. Although clicked together, the query is complex and requires some custom handling to filter out duplicate hits--I just wonder why no one else seems to face that particular problem; Hardly any info on that issue. I hope it's working as expected now.

**Comment by Snater** [comment]
@lucyWMDE I am not sure on the filter result layout any more. I have implemented a masonry-style (Pinterest-like) column layout as to the wireframe. Optically, that's the most pleasing one, because there is no blank space. But it's not without disadvantages. Since it's a column layout, the result list is not as readable, because you can't just easily read line by line due to the vertical positions being shifted. But that's a minor thing here. What made me reconsider, are the sticky data sets. Those will of course also aggregate column-wise; Let's say we have a page length of 24 data sets and 6 sticky data sets, those will all end up in the left column, while on top of the second and (on large screens) third column, there will not be a sticky data set. We could run a sophisticated JavaScript tool to have a row-wise masonry layout, but that seems to be a bit over the top for our two (three on large screens) columns.
Simply aligning the items per row would look a bit awkward, because row heights would vary. I am considering to apply a CSS grid, so we could have each row in the same height. That would produce the most amount of blank space, but I guess the height of the result items (which depends on data set title length, event name lengths etc.) will only vary on a small scale anyway.

**Comment by lucyWMDE** [comment]
I should have noticed this a few days ago... dataset filter categories: thema should be included. Metadaten-Format should not be in there... like filetype I meant to remove it from the specifications in the brief - sorry!

**Comment by lucyWMDE** [comment]
Colours for filter controls - I think we should be consistent between selected and non-selected... objekttyp non-selected seems to be a colour change rather than a fade. I think we should fade here as well. The colour you've chosen for the 2nd level hierarchy seems closer to an appropriate fade colour... could it be a mix-up?

**Comment by lucyWMDE** [comment]
Can we make it possible to select 2 items from one filter category? Eg CC0 and public domain?

**Comment by lucyWMDE** [comment]
Lastly, I think the 2nd level hierarchy should be more distinct somehow... for now it feels a bit confusing though I'm not sure how to fix it. I think it's something to do with the colour logic... that the unselected options are initially paler than the selected options - the logic with the 1st level of the hierarchy is different. The options start out all dark then unselected options are paled out after selection.

**Comment by Snater** [comment]
- Get meta data out and theme in. OK.
- Actually, none is actually a fade. The colours are lightened. It's also not a mix-up, 1st level has $color-deep-teal, 2nd level $color-darker-green. Anyway, you are absolutely right, it appears to be different--I have basically just been looking at the code on that. Will change that.
- I was not sure on the consistency. That is why I implemented filtering similar to the existing site without any great logic (except for the object type). We could allow selecting multiple licenses. Yet, on object type, all filter items are connected with AND to find data sets that feature photographs and maps, for example. On licences the logic would be OR, because AND would not make much sense. I am just not sure the results will be what is expected. That was just my thinking, but it would be no problem to implement that.
- The idea was to visualise the OR logic of each filter in the initial state. That initial state does not exist any more after having selected a first item. It's like, initially: "Show me everything", then "show me just the things belonging to that single item". It could be argued that making the switch to AND in object type when selecting an object type does not fit into the logic, but I wouldn't see it that problematic, because you are entering a new state and just starting to build up the AND selection by selecting a first object type…
 I think there's some nice meaning in that. But we could of course do the other way round: All items dull initially, but since we are showing all results initially that did not feel the right way for me.
 On the current page, all items are de-selected initially, but no results are shown initially--that's a match. I just think the method of resizing the active filter item is a bit problematic in the current page, because it causes the layout to shift.

**Comment by Snater** [comment]
Yet I noticed one inconsistency in the current filter item behaviour: On all filters, except object type, the currently active item should appear inactive when hovering another item. Currently, it looks like the hovered filter item would be added to the active filter item, which is true in the object type filter but not in the other filters.

**Comment by lucyWMDE** [comment]
- mm. You're right about the logic of the fade. Good. Pls ignore me :)
- But I think OR logic is what you'd expect when selecting multiple filter items in one category - for all of them, even objekttyp. I think the use case for looking for datasets that specifically contain more than one objecttype, thema etc will be less common that filtering for, eg, datasets that contain either photographs or film footage. So let's use the OR logic consistently for the whole filter.
- hover... yes - something was strange about the hover... but I think it was more that that hover shows you the future assuming you click, rather than some kind of potential clicking state... Isn't it more normal to have 3 styles? inactive/hover/active... The old site does... can't we come up with something like that? I wouldn't want the enlarged button for active style like on the old site. The inactive and active styles we have in the new site are good. But we need a hover style... perhaps an underline? Unfortunately I can't load the staged site on the ICE WLAN and can't really imagine how it would look.
But anyway - let's add the possibility to combine multiple items with OR logic for all categories.

**Comment by Snater** [comment]
I was trying to get around that OR for all categories, because the event aggregation has ended up being quite complex and I cannot just select an operator as it should be possible for all other filters. I'll see what I can do.

**Comment by Snater** [comment]
Improper filter toggling behaviour was/is a bug in the third-party module, so I have applied an available hotfix. All filters are multi-select now (actually, the object type was already set up for OR)--same applies to #50.
Basically, I am done on these tickets for now.

**Comment by lucyWMDE** [comment]
cool. As for project filter, I think I need to test this out again to be able to give sensible feedback. Let me know when the staging is updated and I'll take a look. thanks!

**Comment by Snater** [comment]
I think we are done with the basics on that. Any upcoming task (including recolouring and any bugs) can be captured by specific tickets.
