### ISSUE TITLE
Project submission form

### ISSUE THREAD

**Issue by Snater** [codingdavinci/relaunch2018#46]
Proper layout and UX of Project submission form.

**Comment by Snater** [comment]
@lucypatterson I guess specifying a language should be possible here as well. Could you also specify character limits here for description and one-sentence description.
Also, I failed accessing the Google form used in the past for collecting project info, which is linked in the Google doc, because it's closed. (My intention is to copy over the proper field titles and field descriptions.)

**Comment by Snater** [comment]
@lucyWMDE: I just noticed that having a character limit on the long descriptions is tricky. A character limit makes real sense on plain text only. But we will have some limited formatting options in the WYSIWYG editor (at least that is what I have implemented for now). With that HTML code being part of the long description, the description would need to be parsed in the front-end (for instant feedback) as well as in the back-end (to check when saving) in order to strip the HTML tags and just count the plain characters. There is no native implementation for that, because it is simply a bit strange. I'd propose to refrain from having a character limit on the long descriptions; In the end, data sets and projects will be reviewed anyway.
That said, a character limit on the one-sentence description is totally valid, because that is plain text.

**Comment by lohengruen** [comment]
I would also need to take a look at the Google Form in order to design a layout. The Text input boxes and the buttons will look the same as on the Login form, but I would probably use a different colour scheme (no coloured background).

**Comment by lohengruen** [comment]
I've designed a basic form layout that can be adapted to most cases. It's basically just a two column layout (that folds to one column on mobile). Lines may also span both columns.
Let me know if this works for you or if you need any specific designs.

https://www.figma.com/file/InrJsaANFIonkhVDwCiyJf/Submission-Form-Design?node-id=0%3A1

**Comment by lucyWMDE** [comment]
@lohengruen - this ticket belongs to work package B. I'll figure out how to stop you getting notifications.

@snater - character limits are important. People submit all kinds of stuff otherwise. Let's use one anyway and set it quite long to accommodate any html. I can write something to explain in the description. Btw - what happens if the submitters paste from MS Word or other rich text editor (likely to happen) - will unnecessary tags be removed?

**Comment by Snater** [comment]
@lucyWMDE OK, no problem. What should the visible character length be? Normally, there shouldn't be too much of HTML. I guess we are going to allow headings, inline links, lists, bold and italic formatting. Adding 10% to what should be set as visible character length should be quite sufficient. And should we be verbose about the actual limit count or just tell the user the description is too long without hinting any max character length?

Since we limit available tags (formatting), any of such not allowed will be stripped automatically when pasting from word using keyboard shortcut.
Although I don't think it's really needed in that case, I will add buttons to the WYSIWYG editor that allow dedicated pasting from Word and pasting as plain text.

**Comment by lucyWMDE** [comment]
Here's a new link to the [old project submission form](https://docs.google.com/a/wikimedia.de/forms/d/1yeRxtyNJTopjOPkRLKrdEqbheDiSytxpTLdOb-mwbbE/edit?usp=drive_web).
I think descriptions are 700-1400 characters. Let's make max character length 1500 for now.

**Comment by Snater** [comment]
While I struggled on some other issue, good news on that: There's a pretty module that does the job of limiting the filtering out the HTML along with limiting the maximum length.
@lucyWMDE Will the short description remain limited to 700 characters as in the Google form?

Just a side note: As mentioned on #35, these forms will not use the front-end theme. I think it is most practical to use the Drupal built-in back-end theme for that. It's not really fancy but most flexible and I think it's fair to display everything behind the login in the back-end theme. If there really is some time left, we can think of implementing the forms using the front-end theme, but I'd really push that to the far end.

**Comment by lucyWMDE** [comment]
Cool. I've updated the max character numbers in the [data specifications doc](https://docs.google.com/document/d/1VUlQ92dvQjpuJEcSssaQ7xhL8NXwCENu1dKv24FFkDM/edit#).

I'm happy with using the standard drupal theme for submission forms.

**Comment by Snater** [comment]
I regard that done, specific issues may be addressed with individual tickets. Like mentioned before, the theme is not really fancy, but I am confident users will get along. We can put some more work into that at a later stage, but I think its definitely good enough for now.
