### ISSUE TITLE
Project filtering

### ISSUE THREAD

**Issue by Snater** [codingdavinci/relaunch2018#50]
Implement view with filter controls.

**Comment by Snater** [comment]
This is basically done (except for the header again). I applied a grid layout on the project filter results but left the masonry layout on the data set archive as it is for now. Could be useful to decide on which aggregation layout to choose. Making the switch is not a big deal--in theory, we could have different layouts as well of course.

**Comment by lucyWMDE** [comment]
not sure about layout on desktop. Mobile and tablet seem fine, but the 5-column layout above a 4 column grid with a button floating in the middle is too weird for me. Can we find a better way to limit this? Also, tbh I don't know why we need the "Filter Anwenden" button - we don't have one on the dataset archive...

**Comment by lucyWMDE** [comment]
ah sorry - I just saw the "Filter Anwenden" and "Zurücksetzen" buttons on the dataset archive page... But still the question - do we really need them? I can imagine having a smaller "Zurücksetzen" link perhaps, but I can't see the point of the "Filter Anwenden" button.

**Comment by Snater** [comment]
I agree on the layout. I just haven't found a better solution at first, I wanted to get the functionality done and have another look at that in an incrementation. Will try to find a better solution.

Oh, yes, the button(s). I wanted to leave the buttons out at first. But then again, I do know people who are not aware that forms can be submitted by pressing Return. I am sure no hackathon participant belongs to that group and I am not pointing fingers on anyone. It's just maybe that some other user group could contain… some… A silly thing is of course that the button is just for the text boxes and for project filtering there is only a single one. I absolutely don't mind removing the button(s). Tell me and I will happily do it! :)
That was just my consideration on that.

(By the way, since we are touching such topics: Firefox removes RSS support in the upcoming version 64, Google had discontinued its RSS reading in 2013. I really think we can leave out the feed for the news.)

**Comment by lucyWMDE** [comment]
cool.
re. buttons - if it applies to the search perhaps we could include the return button inside/with the search field... or at least keep the search field and button together and rename the button (it applies to the search, not the filter). Not sure about the institution filter - is that automatic as well? or do you have to "enter" to activate the filter..

(re RSS - cool - let's remove the RSS feed details. It only affects the news article and news overview headers - I mailed you about them last night. We can just remove that line from the headers)

**Comment by Snater** [comment]
I had kind of all of that in mind. :) Putting the button next to the text box(es) is a little bit inconsistent, because the other filters are submitted along. It's still a button for the whole form. Then again, it might just be ok and the best compromise.
Putting the button into the field as icon would not be obvious enough. And institution would require pressing enter as well. From a visual perspective, I would like to keep the buttons out.

When we plan to connect all filter items per OR (so no exclusive filter items per filter), we could also think about not submitting the form on each click. Instead, the user could mark all filter items first and then hit the filter button. I am not sure what the primary use-case would be. But having to wait for the form each time after selecting a filter item might be a bit awkward, if applying more than, say, 3 filter items would be the standard use-case. Just to bring in another option…

We could have a sophisticated solution by switching the form to AJAX and auto-submit (with a little timeout of 500 to 1000 ms on typing into text fields). That would be quite shiny but might take a bit of time.

**Comment by Snater** [comment]
The institution input box won't submit per Enter because that key is also used for selecting the auto-complete value. It would require some custom coding, but instead of a "global" button, we could place button-styled icons next to each text input element on the same line. The link filters are submitted individually, so I guess the text input(s) could behave just like that--although there's a little inconsistency when filling both text boxes (on data set) and clicking one button, both values will be submitted. But we could regard that a feature.

I have altered the filter layout to match that of the data set filtering for now, so I put the filters into a left column on large viewports.

**Comment by lucyWMDE** [comment]
ok. Let me know when staging is updated and I'll have another look.

**Comment by Snater** [comment]
I sincerely hope that sorting is working properly. Let's tackle all upcoming things on filtering in individual tickets.
