### ISSUE TITLE
Export functionality for filtered project info

### ISSUE THREAD

**Issue by Snater** [codingdavinci/relaunch2018#54]
Functionality to export project info per event.

**Comment by lucyWMDE** [comment]
OK, use cases are:

- editing rounds on the website Beschreibungen
- creating the Programmheft for the Preisverleihung 

so let's export...

- Name des Projekts
- Kurzbeschreibung
- Beschreibung
- Links
- Datensätze (CdV)
- Projekttyp
- Sonstige Hinweise

**Comment by Snater** [comment]
That's done. Users with sufficient permission have links to the export pages under "Verknüpfungen" / "Short cuts" in the admin toolbar / menu. The pages just show previews with a limited set of columns. By clicking the tiny csv button, the whole bunch of columns can be downloaded as csv.
