### ISSUE TITLE
"Weiter" button submits form

### ISSUE THREAD

**Issue by Snater** [codingdavinci/relaunch2018#55]
"Weiter"/"Zurück" buttons on the data set submission form trigger form validation if title field is not filled / submit the form when title field is filled instead of just switching to the next/previous tab.

**Comment by lucyWMDE** [comment]
let's talk about this. Institutions will likely fill out the form in more than one sitting as they might not have all the required information to hand in the first attempt. Also, I'm assuming some fields can be marked as optional, others as Pflicht...?

**Comment by Snater** [comment]
This issue was just about some unintended behaviour.
Except for the title, there are no required fields at the moment, as that seems to be the case in that Google form. The form sections are just visually broken up into tabs to not have all fields in one huge form (although it remains one huge form technically and logically) and the buttons to continue / go back are just switching the tab panes.
If there should be additional required fields, I can mark such as required easily, it just needs to be defined.
