### ISSUE TITLE
Restructure Project team contact details

### ISSUE THREAD

**Issue by Snater** [codingdavinci/relaunch2018#56]
Add optional contact details per team member.

**Comment by Snater** [comment]
@lucyWMDE I am not sure, it's what is intended, but that made sense for me from a technical 
perspective:

## TEAM MEMBERS
### Team Member
Name:
[__________]

E-Mail:
[__________]

#### Links
URL:
[__________]

optional link text:
[__________]

[ADD LINK]

[ADD TEAM MEMBER]

---
I could also implement: 

## TEAM MEMBERS
### Team Member
Name:
[__________]

[ADD EMAIL]
[ADD LINK]

[ADD TEAM MEMBER]

Technically, that would be more complex, because additional Paragraph instances need to be created for e-mail and link and both would need to be references separately for having two individual buttons to add email and link, that would also need to be considered when rendering in the front-end.

If it's rather common for team members to provide an email address and a link, I'd go for the currently implemented option anyway. No fields are required at the moment, so fields could just be left blank.

**Comment by lucyWMDE** [comment]
we can describe it in such a way that it's clear email is not necessarily a preference, and that it's also possible to leave contact details blank.
