### ISSUE TITLE
Apply two-column layout to checkboxes in submission forms

### ISSUE THREAD

**Issue by Snater** [codingdavinci/relaunch2018#62]

**Comment by Snater** [comment]
Looks fine, but does not work on the object types and files types checkboxes, because, due to Drupal rendering, the HTML is not hierarchically structured, so unfolded categories of an object type / file type extensions of a file type could unintentionally wrap to the next column. This could also be solved, but would require some more work.

**Comment by lucyWMDE** [comment]
let's leave it as it is - not so important.
