### ISSUE TITLE
DSGVO compliant data submission 

### ISSUE THREAD

**Issue by lucyWMDE** [codingdavinci/relaunch2018#63]
For both project and dataset submission - we will need to include some declaration check boxes. Text to be defined.

**Comment by Snater** [comment]
That's low hanging fruit I'd like to pick. :) Shall I insert a placeholder text? (Could be replaced any time now or later.)

**Comment by lucyWMDE** [comment]
go for it :)

**Comment by Snater** [comment]
Should be done.
