### ISSUE TITLE
Event Section

### ISSUE THREAD

**Issue by samu-wmde** [codingdavinci/relaunch2018#7]
User Storie: As a regional organiser I want clear link to my upcoming/ongoing event on the landing page so that my participants can find me. 

Comment Design: 
Each upcoming/ongoing event (we expect 1-3 at any one time) represented with a tile with basic info (where, when) prominent on landing page. Same tiles as used on event overview page.
Comment Dev: 
Tiles manually created and edited in html (from templates). Same as on event overview page.

**Comment by lohengruen** [comment]
This is the basic box design for the event overview.
(Box sizes may change, depending on the key visuals)

https://www.figma.com/file/lLxLCHZL95ReAyDSwQ97ok/EventsOverview-Boxes-Design?node-id=0%3A1

**Comment by lohengruen** [comment]
Is there still something you need from me for the regional identity? Or are you blocked because you need the actual logos for the next events, not just placeholders?

**Comment by Snater** [comment]
Thanks, I'm not perfectly sure. I haven't dealt with implementing regional identity yet, because it has yet to be approved. So there's nothing you can help with at the moment. Might get back to you as soon as that's ready to go. Last piece of the puzzle here. :)

**Comment by Snater** [comment]
Just as on #2, there's just some minimal event individualization in place for now.
