### ISSUE TITLE
Sync number of news articles displayed with number of upcoming events

### ISSUE THREAD

**Issue by Snater** [codingdavinci/relaunch2018#75]
That might be a funny one…

**Comment by lucyWMDE** [comment]
also, it shouldn't look as though the news teasers belong to the upcoming regional event logos... eg. 2 logos and 2 news teasers should be avoided. We should be able to address that once we know how big the logos are by adjusting the length of the news teasers.

**Comment by Snater** [comment]
I'm a bit confused on that. I thought the idea was to have a n-to-n relationship now. (But I remember the discussion that this would lead to relating news items to the events.) So it should rather not be n-to-n – rather some even-to-odd and vice versa relationship with news block and event block having kind of the same height. Is that correct? Either way it's tricky to have that properly considered on all layout breakpoints. We might even want to have different teaser lengths per setup, if we have like 1 event - 2 news items | 2 events - 3 news items.
I'll just put that to the end of the todo list.

**Comment by lucyWMDE** [comment]
> rather some even-to-odd and vice versa relationship with news block and event block having kind of the same height

yup - that's it. The whole block for either events or news should be the same height, but it would be bad if eg there were 2 events and 2 news items that lined up with each other. My assumption would be that making sure  news items and event logos are significantly different in height should at least be part of the solution.

**Comment by Snater** [comment]
I'm sorry, I tried it, but it does not work out properly. You should take a look at some point when the staging is updated and we can change that. But as I see it, an event item cannot be higher than a news item or we would need to strip down the teaser length to just a few characters (if at all).  Having less news articles than event previews does not really work out. In the end, having the same number of news items and event previews is just OK. The offset is visible in my opinion. I'd rather try to figure out a way to better separate both sections visually.
Closing as I am done on that for now.
