### ISSUE TITLE
Content/Abschnitte/Text: Table überschrift not styled/visible.

### ISSUE THREAD

**Issue by lucyWMDE** [codingdavinci/relaunch2018#86]
eg. http://codingdavinci.snater.com/de/events/ost-2018 tables all created with Überschriften but überschriften aren't visible in Ansicht.
Style should be similar to: https://www.figma.com/file/W0R4yR7orXG7JhEXlw3Mv6/EventPage-Modules?node-id=0%3A1

**Comment by Snater** [comment]
Not sure why the previous styling did not work any more.
