### ISSUE TITLE
Content/Abschnitte/Text-Intro: increase padding above text

### ISSUE THREAD

**Issue by lucyWMDE** [codingdavinci/relaunch2018#87]
We discussed this already at an earlier stage - we need to increase the padding above the text in this paragraph so that it doesn't run so close to the top of the page. Maybe the edit got lost?

**Comment by Snater** [comment]
Not perfectly sure. Could you provide a screenshot, please?

**Comment by lucyWMDE** [comment]
![image](https://user-images.githubusercontent.com/42772674/61067893-fd6d4080-a408-11e9-8207-7a757a98c3bf.png)
the padding above "Das Jahr..." it's currently set in .layout-container--wrapper.header-tiles-above .layout-container main .layout-content at 30px - in the screenshot I increased it to 70px which looks better to me. It's because the left and right margins are so big, it looks a bit squeezed to the top of the section without more padding.

**Comment by Snater** [comment]
OK, I assumed it was something more general to change. I changed that particular padding. Should be OK now.
