### ISSUE TITLE
Projekte: page won't load ┐(´ー｀)┌

### ISSUE THREAD

**Issue by lucyWMDE** [codingdavinci/relaunch2018#89]
http://codingdavinci.snater.com/de/projekte 
Seems there's a general problem, maybe with the import - see also issue #90 

Many project pages also not loading:
http://codingdavinci.snater.com/de/projekte/mnemosyne
http://codingdavinci.snater.com/de/projekte/skelex
http://codingdavinci.snater.com/de/projekte/ethnoband
http://codingdavinci.snater.com/de/projekte/ethnotier
http://codingdavinci.snater.com/de/projekte/grips-theater-plakatarchiv

These do load, however:
http://codingdavinci.snater.com/de/projekte/math-models
http://codingdavinci.snater.com/de/projekte/kleid-er-leben
http://codingdavinci.snater.com/de/projekte/artific

no idea what the difference is...

**Comment by Snater** [comment]
These had no reference to an event. Fixed that, works without event reference as well now.
