### ISSUE TITLE
Project Section 

### ISSUE THREAD

**Issue by samu-wmde** [codingdavinci/relaunch2018#9]
User Storie: As a founder I want to show highlighted projects on landing page so that I can easily convince GLAM institutions to participate.

Designer Comments: 
Curated collection of highlights. Carousel? Visual: image, project name, 1-sentence description, link

Developer:
BASIC: each project presentation manually created and edited in html (from templates).
NICE-TO-HAVE: founders make a selection and projects presentations on the landing page are automatically generated from archive data.

**Comment by Snater** [comment]
We could use something like https://github.com/gridstack/gridstack.js (http://gridstackjs.com/) or https://github.com/Vestride/Shuffle (https://vestride.github.io/Shuffle/) – both MIT licensed.

**Comment by lohengruen** [comment]
Wireframe
https://www.figma.com/file/gl8B5zKtevNJGJ2YAxtVAd/Projects-Wireframe?node-id=2%3A3

**Comment by lohengruen** [comment]
Also, I really like the idea of using gridstack for the landing page.
Shuffle feels even nicer, but I can see its features more used in the Projects Overview or the Data Overview.

**Comment by Snater** [comment]
Implemented.
