### ISSUE TITLE
Datasets: possible additional field - Gesamtzahl Mediendateien Letzter Stand

### ISSUE THREAD

**Issue by lucyWMDE** [codingdavinci/relaunch2018#91]
> - can we (easily) change dataset field for Gesamtzahl Mediendateien from 
> numeric to alphanumeric? It would be nice to add a qualifier eg "Stand 
> May 2019".
Unfortunately no, because each field's data type maps to the data type
used in the database table. In that case, it's an integer data type.
However, in terms of data consistency, I would not recommend changing
the field data type anyhow and rather add another (optional) field for
supplying additional information.

Question to Philippe/Ilias: how important is this feature?

**Comment by ikyriazi** [comment]
I personally don't find it that importart; if sum of files changes (which I would expect though to be fixed after being submitted), we will just have the new sum there.

**Comment by lucyWMDE** [comment]
cool. Sounds like a nice-to-have, but let's check with Philippe when he's back - I think this feature request was from him...

**Comment by ikyriazi** [comment]
Hi, Lucy! For Philippe this is also not an important feature (the initial comment was not from him).
