### ISSUE TITLE
Datasets: taxonomy terms hidden from some users ("unklar" issue)

### ISSUE THREAD

**Issue by lucyWMDE** [codingdavinci/relaunch2018#92]
> - Philippe from the Geschäftstelle has been adding new structured 
> metadata to the imported datasets. We have a problem with licenses in 
> that we don't always have details of the license /version/. So far,
> Philippe has labeled all these "unklar" (we created a temporary new 
> taxonomy term). We won't be able to clarify them all before the 
> relaunch. SO... we would like to use generic taxonomy terms "CC-BY" or 
> "CC-BY-SA" for these legacy datasets. BUT it's important that they not 
> be available for use by future submitting institutions. How can we make 
> that possible?
It would be nice if terms could only be made available to particular
user groups. Since that's not possible, the most dirty hack I can think
of is to inject some JavaScript that would remove those legacy options
from the license select box specifically for insitution users.

Question: do we need this feature?

**Comment by lucyWMDE** [comment]
unfortunately I think we need this feature... Can you do it?

**Comment by Snater** [comment]
I have a applied a more or less minimal change here, which could be refined if needed: For users belonging to the admin or office (Geschäftsstelle) group, all licenses taxonomy terms will be available for selection, while other users (institution) will, just as before, only be able to select all licenses that have no parent item (see licenses taxonomy tree at `/admin/structure/taxonomy/manage/licenses/overview`). This is a pretty clean and simple solution, it might just be confusing that some terms repeat (unklar > unklar)—the simplest thing would be solve that by just renaming the parent taxonomy item(s).

**Comment by lucyWMDE** [comment]
that's great - thanks Henning. We won't need the unklar term(s) by the time we launch - they were only a stop-gap. We should be able to work very well with what we have now.
