### ISSUE TITLE
News: additional paragraphs

### ISSUE THREAD

**Issue by lucyWMDE** [codingdavinci/relaunch2018#95]
> - Seems like we really need additional image fields in news articles. 
> Currently we only have full width... but we need to be able to work with 
> smaller images. eg to add logos. Can we add some additional paragraph 
> types? Or can we add images into the textbox?
Both would be possible. But on that content type, I'd recommend adding
additional paragraphs to keep that single mode of creating content and
having images added as media - instead of uploading them directly to the
node.

**Comment by lucyWMDE** [comment]
Sounds like the right thing to do. I hope the styling isn't complicated...

**Comment by Snater** [comment]
When looking at this again, I am unsure what to implement exactly. Could you outline which fields you would need in those additional paragraphs / what elements should be in the paragraphs? Or could we just reuse existing paragraphs used on the events? We have the paragraphs "Textblock links / rechts" and "Logos" for example.

**Comment by lucyWMDE** [comment]
waiting to take a look at the front end of the Über page (#103) before I can make a good decision here.

**Comment by Snater** [comment]
Closing as duplicate then.
