### ISSUE TITLE
language versions

### ISSUE THREAD

**Issue by lucyWMDE** [codingdavinci/relaunch2018#97]
> - I can't figure out how to make English versions of top level pages? eg 
> Daten. I've translated the whole filter taxonomy, but maybe you need to 
> make the English version of the dataset archive? It would be great to 
> make all of these if that's something out of the reach of admin user.
First, a module required to do that was not installed. But the way to
translate such pages might not be obvious anyway: Structure > Views and
there you select "Translate" fomr the drop-down button of the view (e.g.
Datensätze). In the column "DISPLAYS" you can see on which paths each
view is being used, which might help you to better identify whcih views
you want to translate.

...to document

**Comment by lucyWMDE** [comment]
finally found the right fields for the translations... confusing because they are a long way down in a tree structure, often in sections marked "LEER"... not user-friendly... but I suppose they shouldn't be changed that often. here be dragons.

**Comment by lucyWMDE** [comment]
So - all relevant fields have been translated, but I still don't get an option to switch language with the menubar language switcher... I have to manually change the url (eg from http://codingdavinci.snater.com/de/daten to http://codingdavinci.snater.com/en/daten). How can we activate this?

**Comment by Snater** [comment]
This was a limitation of the custom language switcher implementation. I have enabled language switching on all views (Anzeigen) in general, so it's also enabled on the project listing. Could implemented some more sophisticated logic checking the view and its specific setting(s), but I assume it's sufficient as it is with this change.
