### ISSUE TITLE
character limits

### ISSUE THREAD

**Issue by lucyWMDE** [codingdavinci/relaunch2018#98]
> - how do you adjust character limits on text? I've looked for it but 
> with no luck. Some legacy dataset descriptions from the old site are too 
> long to fit and have been imported with the end missing. That's ok - we 
> can copy-paste over by hand... but is there a way to increase the 
> character limit to edit those texts, then have a shorter character limit 
> going forward?
Structure > Content types > (Datensatz) Manage for display [Dropdown
Button] > Cog at "Beschreibung"

...to document

**Comment by lucyWMDE** [comment]
Henning - this works as a solution for now. 
e.g. [this dataset](http://codingdavinci.snater.com/de/daten/digitalisierte-historische-zeitungen) has a description over 8000 characters long (it is a very complicated dataset, so it makes sense in this case). The maximum length we'd previously set was 1500 characters. I think we could up this to 2000 characters, but not more. It was possible to temporarily set the max character limit for the field to 10 000, make the edits, then return the max character limit to 2000 - the text was not shortened. However, opening the dataset in edit mode results in automatic shortening of the text. Is there any way we can avoid this happening?

**Comment by Snater** [comment]
The maximum length seems to be enforced on a hook that is triggered when saving the node—it's the most sensible place to put that logic.
The feature you are requesting would be a bit against the logic and intention of that max length module. But I could have a look, whether I could just "circumvent" the character limit when a node is saved by a user of particular user groups (admin user, Geschäftsstelle, maybe Project Team as well). That might very well be possible and would actually be an OK solution.
Alternatively, it would be possible to hack something in, but we should stay away from that: An option would, for example, be to have a legacy field, only available to certain user groups, where an unlimited amount of characters could be entered.

**Comment by lucyWMDE** [comment]
The re-saving issue could apply to all user-groups (eg Institution user is just as likely to want to update their dataset info as any regional organiser or even admin user). An additional text field for legacy text, hidden from the Institution user in the submission form, would probably be the better solution. If the institution wants to edit it they have to get in touch with the Geschäftstelle.

**Comment by Snater** [comment]
Added an unconstrained description field available to admin and office (Geschäftsstelle) users only. I was not sure about some logic. For now, the unconstrained description will simply appear below the normal description.
